### ISSUE TITLE
provide hooks for external event loop integration

### ISSUE THREAD

**Issue by garlick** [openpmix/openpmix#102]
This is a feature request for hooks to allow (server side) PMIx to be integrated with an external event loop, not necessarily libevent.

When RM code is already using event-based programming, having PMIx callbacks run in the context of a seprarate PMIx server thread requires synchronization that would not be necessary if the PMIx callbacks were driven by events in the RM thread.

Other libraries have evolved interfaces for external event loop integration.  For example see [libadns](http://www.chiark.greenend.org.uk/~ian/adns/docs/adns.h.txt) - specifically `adns_beforepoll()` and `adns_afterpoll()`.  The idea is to find out what fds and timeouts PMIx needs to poll on in the first call, and then when one of those is ready, give PMIx control in the second call, until it would block, e.g. run the libevent loop with EVLOOP_NONBLOCK.

The adns example is discussed with sample pseudo-code in the [libev manual](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#Watcher_Specific_Functions_and_Data_-8) in the context of embedding other event loops in libev.

See also pr #100 discussion

**Comment by rhc54** [comment]
Hmm..ok, let me take a shot at it.

**Comment by rhc54** [comment]
@garlick I see a few alternatives. You had previously requested the ability to pass the file descriptor a client should use when talking to the PMIx server library. All our events are initiated via messages. What if we give the client an option to pickup an fd passed in its environment so you can directly control its servicing, and then provide a "deliver message" interface by which you can pass it to us for processing? You could tell us the fd you want to assign to that client when you register it so we can ensure the envar is recognized.

The "deliver message" interface could include some kind of callback mechanism that lets us indicate that we need to push an event for you to progress so you know if we are done or need further servicing.

Make sense?

@ggouaillardet Would you have interest in implementing this? Any suggestions on methods?

**Comment by garlick** [comment]
I'm not entirely clear - in this mode is there still a pmix service thread started by the library, or is everything now happening in the thread that calls `pmix_server_init()`?

As long as "my" thread doesn't block in pmix calls, and doesn't get callbacks in the context of a separate pmix service thread (thus requiring my code to be reentrant), then this should be doable.

**Comment by rhc54** [comment]
There would be no service thread in the PMIx server library. Your service thread would "own" monitoring the fd, but would call a new PMIx API whenever the fd "fired" as we would have to read the incoming data (it consists of a PMIx-defined header plus data fields). I'd have to work thru the details in our code, but we can guarantee that all callbacks will be in the context of your service thread.

Alternatively, we could provide detailed documentation on the wire protocol we use in the library, and then create a new "deliver message" API for when you receive something from a local client. We'd have to figure out the code path thru that entry point to ensure we don't block somewhere. Negative here is that you would have to maintain things  if we make some internal change to the pmix library.

The devil is always in the detail. I'd just like to find a solution short of you re-implementing the entire server as that is a lot of complex code. Do you have a preference as to approach?

**Comment by garlick** [comment]
> Negative here is that you would have to maintain things if we make some internal change to the pmix library

That sounds like the wrong move then.

Would there just be one fd to manage, or a dyanamic set?  Presumably timeouts would need to be handled too?

**Comment by rhc54** [comment]
It would have to be a dynamic set as clients and tools connected and disconnected. We currently call ```select``` with a timeout of 2 seconds, but the precise value doesn't matter. Timeouts are present just to allow us to check for termination.

You know, the alternative to all this is to perhaps do as we did in OMPI: take PMIx callbacks and "thread shift" them to the local service thread. What we do is create an object, point to the incoming data (since all calls into the host daemon are non-blocking and require the data to be held until callback), generate a local event that includes the object, and then let the local service thread's event handler process the request. When done, you call the provided PMIx server callback - the server library expects that callback to be in your service thread and it automatically "thread shifts" the response back to its own thread.

It introduces some delay in the processing loop, but PMIx isn't in a performant scenario...and it means your code doesn't have to be reentrant (ours certainly isn't). Would that be an option for you?

**Comment by garlick** [comment]
Hmm.   I think you already "thread shift" pmix_server function calls from the user to the pmix thread(?) What about doing the same in the opposite direction and signaling a "mailbox fd" that the user polls on?  Whenever mailbox becomes ready, user calls `pmix_process_callbacks()` or similar, and callbacks occur in the user's thread?  (That might require there to be a queue of callback results and a special fd to indicate when there's a result available)

This is kind of how zeromq works.  It starts its own thread to manage message queues and assemble whole messages from bits on the wire, then provides event loop integration through a "mailbox fd" and event mask accessor, per zeromq "socket" (not an actual socket).

See ZMQ_FD and ZMQ_EVENTS in  http://api.zeromq.org/4-2:zmq-getsockopt

**Comment by rhc54** [comment]
Hmmm...yeah, I think we could do something like that. I'll see if I can prototype it - might take me a bit, but I'll let you know when I have something worth poking at.

**Comment by garlick** [comment]
Cool!  No rush, we have other priorities right now on the Flux project, but would be nice to have something we can work with to circle back to!

**Comment by jjhursey** [comment]
We have been chatting off-list a bit about this ticket. Let me try to summarize, then we can continue the conversation here.

The goal is to give the RM a different means of controlling when events/callbacks occur from PMIx into the RM. Currently, PMIx will trigger the callback in the PMIx CL's support thread (where the PMIx CL thread-shifts work). As an alternative, PMIx would provide a set of interfaces to allow the RM to control the context in which those callbacks occur. More precisely, in the context of a polling thread inside the RM. The RM can choose one or the other technique at server initialization time.

There are many ways to approach this. One suggestion was for the following (modeled after `ZMQ_EVENTS` and `ZMQ_FD`:
```
// return a mask of pending events (POLLIN, POLLOUT, POLLERR) from pmix
PMIx_server_pollevents(pmix_server_handle)

// return a file descriptor that becomes readable (POLLIN) when events are pending
PMIx_server_pollfd(pmix_server_handle)
```

The RM can then use these two interfaces to test for PMIx events (via `PMIx_server_pollevents`) or to block on the fd becoming readable in `PMIx_server_pollfd`. Once an event is pending, then the RM can call the following PMIx API to activate that event (or the whole queue of events in sequence) in the context of the calling thread:
```
// process PMIx internal events until would block
PMIx_server_process(pmix_server_handle)
```

I need to dig around in the code a bit to see how best to approach implementing this feature.

**Comment by garlick** [comment]
Thanks @jjhursey!  It occurred to me after I sent the above suggestion that I'm not sure why pollevents needs to return a mask of events if it's only ever going to call one function.

There might also need to be a way to retrieve the minimum timeout that's in play before blocking, so the RM can set a timer to wake up and call into PMIx to service that as well.

**Comment by rhc54** [comment]
Looks fine to me - thx! You'll need to define the handle somewhat flexibly as the different
server->host calls pass very different information, but that should be doable.

All the host->server calls are thread-protected in the PMIx library, so no problem having flux directly call them. Since most of those calls have an "ack" callback associated with them (mostly intended to allow the RM to cleanup any data it provided), you'll have to figure out how you want to address those. I suppose you could just push them into the polling queue, if the performance is acceptable to @garlick.

**Comment by garlick** [comment]
Does the PMIx server thread start up in this model, or can the event loop be entered and exited rom the RM's thread via `PMIx_server_process()` (or whatever)?

**Comment by rhc54** [comment]
I'm assuming that the internal PMIx thread would indeed be running, just so it could progress asynchronously. It would then create a FIFO with calls for you to service.

However, @jjhursey may have another idea.

**Comment by rhc54** [comment]
You know, another possibility would be to setup a pipe between flux and pmix, and then have pmix simply push a header+object into the pipe instead of doing a callback. You could then just monitor the pipe for "ready for read" and grab the "handle". Would allow you to be more event-driven as opposed to polling.

**Comment by rhc54** [comment]
Got it. What I was trying to figure out is how to let you know that there is something to process so you'll know you need to call that pmix function to get the info? I figured a pipe might be the easiest way since all event libraries will support it. I was hoping to avoid making you loop over calling the function just in case something was there.

Alternatively, we could create a "flux" plugin that would push events into your thread system.

**Comment by garlick** [comment]
> Alternatively, we could create a "flux" plugin that would push events into your thread system.

That would be concerning.  Was hoping this issue would solve a general API deficiency, not create new code paths that only Flux will use.

**Comment by rhc54** [comment]
I'm not aware of anyone else interested in this approach, regardless of the final mechanism. Other RMs are just taking the upcall from the PMIx server and "thread-shifting" it into their own threads. When they call down into the PMIx server, we always thread-shift into our threads any way.

Not passing any judgement on this conversation at all - I'm willing to put any interface in if it would help someone. Just indicating that yes, indeed, this is almost certainly a code path that would solely be used by Flux, at least until someone down the road decides to follow it.

**Comment by garlick** [comment]
Not passing judgement either, just want to avoid interfaces that may become brittle over time, plus hey, extra maintenance headaches for you.  If the proposal is to add serialization for this pipe for all pmix->RM communication, but only use it for flux, then maybe we should back up and rethink? 

Is there some way to factor the libevent loop so that there is an inner one that calls EVLOOP_NONBLOCK, and an outer one in the pmix thread that uses the pollevents/pollfd style interface to run the inner one when there is work to do?   Then flux or other event-driven code could share common code with PMIx internals.

epoll(2) is one way to give out a single fd that can act as a proxy for a dynamic set of internal fd's.  There are probably other ways as well on modern linux.

I guess the existing, thread-shifting PMIx calls would need to have non-thread shifting counterparts, but again the thread-shifting ones could be built on the non-thread shifting ones right?

**Comment by rhc54** [comment]
That sounds good. As I said, we are prepared and willing to do whatever it takes to make this work for you, but obviously the path of least effort is appealing 😄 

Let us know how we can be of help. I think we'd all like to see Flux/PMIx working together!

**Comment by rhc54** [comment]
BTW: thanks for the explanation. It truly helped me to understand the situation.

**Comment by garlick** [comment]
My apologies for not being clear before then!  Thanks to you and Josh for being willing to help.

**Comment by jjhursey** [comment]
I've not forgotten about this, just got pulled into something else this week. I'm hoping to get back to tinkering with it this weekend.

I was thinking that we might be able to simplify the interface down to a single call.
```
/*
 * Progress all pending PMIx callbacks in this thread context.
 * If no events are ready to be progressed, then this call returns 0 immediately.
 * Returns the number of events progressed.
 */
int pmix_progress(void);
```

Then all of the marshalling of the queue/pipe is handled inside PMIx. The RM can then just call the progress function when it's ready to handle those events.

We could add some arguments to allow for the caller to express how many events to progress, but I don't know if that would be useful or not.

**Comment by garlick** [comment]
sounds good, though the caller needs to be able to go to sleep in it's
event loop when there is nothing to do, hence the need to expose a fd that
becomes readable when new work arrives (or an equivalent mechanism).  Busy
polling the proposed function would be a bad thing IMHO.

**Comment by garlick** [comment]
I just reread your post and realized you were just talking about having one function to call to handle events, not eliminating the queue/pipe.  Sounds good!  Sorry I missed that earlier.

**Comment by rhc54** [comment]
I think this has died for lack of cycles - let's close it for now and reconsider options if the need arises.

**Comment by garlick** [comment]
Nice!

Is there some way to get a file descriptor that becomes readable (or similar) when there is work to do, or does one have call `PMIx_Progress()` periodically?

**Comment by rhc54** [comment]
Hmmm...it might be easier if you passed into us a file descriptor (i.e., the write end of a pipe) that we could just write a byte into when an internal event occurs that needs progress. The only issue there is that (for example) the client library can't detect that the server sent it a message (for an event or to return information from a request) unless the library is progressed. So while we could tell you when the library has generated something internally that needs progress, we cannot tell you that something external is trying to communicate to us. Only way to handle that would be to periodically call `PMIx_Progress`.

Would a combination of the two help? We could "tickle" you with the pipe when something internal happens that needs progress, and you could periodically progress the library (perhaps less frequently than without the "tickle" support) to ensure we picked up communications. It'll slow down the PMIx response rate, but would let you reduce the frequency of calling "progress".

FWIW: in the absence of a pending event, the progress function returns rather quickly - I haven't measured it, but it's the same progress function that OMPI has in its MPI critical path, so it is a performant operation.

**Comment by garlick** [comment]
If providing a hybrid file descriptor from `epoll(2)` or whatever won't work (and I sympathize as it's Linux specific), what about an interface that would let a pollfd array (or similar) and a min timeout value to be fetched?   The external event loop could fetch those right before blocking and arrange to be woken up when `PMIx_Progress()` needs service.

I think something like that is needed to complete the interface, otherwise we'll have to deal with the torches and pitchforks when the noise aware citizenry figures out we're waking up every 100ms or whatever on compute nodes.

**Comment by rhc54** [comment]
I have no issue with using `epoll` and limiting that usage to Linux - I don't view this interface as being something non-Linux users (e.g., Windows or OS-X) would care about. If they do someday, then they can easily provide an alternative - meantime, they can just use the internal progress thread.

The more I kanoodle this, the more I find myself wondering if we are missing something. Let's review this for a minute. PMIx already uses epoll (via libevent) to monitor the communication file descriptor and internal processing triggers (actions inside the library are executed as an event-driven state machine) so it knows when the library needs attention. Libevent has a progress interface (event_loop) that one must call so the library will block waiting for an epoll event to fire.

`PMIx_Progress` simply calls `event_loop`. So when the host calls `PMIx_Progress`, it is going to block in that function until the PMIx library gets an event and completes processing it. This is when libevent returns from the `event_loop` call.

IIRC, libevent won't sit in that function forever - it will return from it after some time in the absence of an epoll event, just to give the host a chance to decide that it should quit waiting. I'm not sure what the wakeup time is - it might be controllable. I'd have to check. However, once we pop out of `event_loop`, we cannot know if anything needs to be done (message received or whatever) until we go back into that function - libevent won't tell us something needs doing unless we are in the event loop.

I don't see any real way to generate an asynchronous event that tells the host to call `PMIx_Progress` - we would need an event to wake PMIx up so it can notify the host that the host needs to call "progress", but we need to be in the event_loop in order to get the original event. I think we have a circular logic problem ☹️ 

So I believe we are stuck with the host having to periodically call `PMIx_Progress` and block in that function until libevent times out or PMIx gets a libevent epoll event and processes the corresponding operation. How frequently one dives back into `PMIx_Progress` is, of course, up to the host. It only impacts responsiveness. The fact that the calling thread would be blocked in `PMIx_Progress` may also cause its own problems.

I guess the question then becomes: is this any better than our internal progress thread? As I said, it already uses epoll (via libevent) to monitor when the library needs attention, and the progress thread is blocked until that happens or the event loop times out. Other than the host perhaps delaying the return to blocking in libevent's event_loop, isn't this the behavior we are trying to achieve with this change?

If so, then would another (possibly simpler) approach be to provide an attribute that injects a time delay between calls into `event_loop`? Possibly calling `nanosleep` for the specified time before re-entering the loop? Just wondering if this doesn't buy us the same benefit without requiring the host to do something special.

**Comment by garlick** [comment]
Rewinding a bit, the use case that motivated this issue is embedding the PMIx server in a single-threaded, event driven program that has its own event loop (libev based in our case).  What's needed is a way to nest the two event loops so that we 1) never block when there is work to do, and 2) never wake up when there is not (or at least rarely and not regularly).

As the "user", the flux shell would be the outer event loop, and as the library provider, PMIx would be the inner event loop.

> PMIx_Progress simply calls event_loop. So when the host calls PMIx_Progress, it is going to block in that function until the PMIx library gets an event and completes processing it. This is when libevent returns from the event_loop call.

That violates 1) above.    I'm not that familiar with libevent but I think you could use the `EVLOOP_NONBLOCK` flag rather than `EVLOOP_ONCE`?

To achieve 2) the outer loop needs a way to integrate the inner's event sources with its own in its call to `poll2(2)`. That's what I was trying to get to above.  If you lose track of your file descriptors when they are passed to libevent then again I sympathize - you'd need some way to track them which probably means digging inside or wrapping it.

The epoll trick is really just a neat way to aggregate event sources into a single file descriptor to provide a clean API for it, since asking for an array of file descriptors and their poll flags is going to be a bit ugly.

>  I guess the question then becomes: is this any better than our internal progress thread?

Er, not from the perspective of event loop integration.   Last time I tried to figure out how to make it work with the PMIx server callbacks being made in the PMIx server thread context I got stuck and opened this bug.  Possibly I'm missing some nice way to make that work though.

**Comment by garlick** [comment]
Oh sorry, I just answered that last question in reverse.  Yeah it's a little better but probably doesn't quite get there for us.

**Comment by rhc54** [comment]
We could certainly change `PMIx_Progress` to use `EVLOOP_NONBLOCK` - I'm not sure of all the side-effects of doing that, so it would bear some investigation. However, it sounds like you actually want the file descriptors themselves so you can "poll" them - which means that even with the change, it doesn't sounds like this new API is going to help resolve it. Even if we found a way to pass up the file descriptor monitoring the communication subsystem, it wouldn't help with the async state machine as that doesn't use an fd - it just uses libevent's internal triggers. You'll only be able to see that a message arrived or needs to be sent - you won't complete any of the operations required to process that message or the operation it requested.

Side note: PMIx supports libev as well as libevent nowadays. From our tests, libev behaves the same as libevent - you can block in his event_loop equivalent until either one of the fd's fires or it times out, and then you have to re-enter it again. It also times out regularly to give you a chance to make decisions (e.g., "let's not continue") ala libevent. 🤷‍♂️  We haven't found any real benefit of going either way, but that's just our experience. Would welcome your comments on the difference (perhaps separate from here).

I think what I was trying to get at with my previous comment was that just letting PMIx operate with its own progress thread gets you to both 1) and 2) since that is exactly its internal behavior (you can always configure the lib with libev to avoid library confusion). Not sure I see the issue with having two progress threads versus one, so long as they both meet those two criteria. It sounds instead like the real issue here may be server upcall integration as you don't have a service thread you can switch the call over to given that you are single-threaded. Is that an accurate assessment?

If so, then perhaps we should focus on that issue as I think we may have already tried to address it, albeit in a separate context. You don't have to threadshift the upcalls - you can process them in the PMIx thread and simply return a `PMIX_OPERATION_SUCCEEDED` response to indicate that you performed the operation atomically (or an error code to indicate that it failed). We added that a while back to support single-threaded hosts. You do have to protect any globals that are used in the upcall function, of course.

Would that (perhaps with additional mods to resolve any related issues) address the root-cause here? If that doesn't quite do it, but the focus should be on the upcall thread issues, then perhaps we can figure out how to further resolve that issue.

**Comment by garlick** [comment]
This issue is specifically about "event loop integration" so shall we re-close it assuming that's not the way to go?

Maybe as you say there are other ways to get this working.  I'm not sure I understand the new functionality you're asking me about, but maybe when we're ready to get our hands dirty on code again, we can have a fresh look at the server side API and open new issues against anything we find problematic?

**Comment by rhc54** [comment]
That makes sense - meantime, I'll take a look at the server-side function module interfaces. I'm wondering if we perhaps need to create some atomistic versions to better support single-threaded hosts - there might be one or two that don't do that so simply today.

I'll go ahead and close this - let's definitely plan on circling back, and I'll post anything I turn up in my investigations on a new issue.
