### ISSUE TITLE
PMIx end-to-end testing improvements

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#1285]
**Per telecon 05/23/2019:**
Recently found issues exposed the need in more extensive testing of the PMIx itself and its integration.
The following items were discussed:
* Need to track the status of existing integrations. In the past, we had issues with Slurm integration (https://github.com/pmix/pmix/issues/1082). Currently, PRRTE has issues. Below is the list of server- and client-side integrations that would be nice to test periodically in order to avoid this kind of issues.
  * PRRTE, Slurm, JSM
  * Open MPI, MPICH 
* Need to come up with the set of configurations (combinations of components) that we would like to test [[discussion-summary](https://github.com/pmix/pmix/issues/1285#issuecomment-495472989)].
* Need to revisit the set of tests that we are running as part of make check to make sure that we have good coverage. [[discussion-summary](https://github.com/pmix/pmix/issues/1285#issuecomment-495473319)].

**Comment by artpol84** [comment]
Let's keep the summary on the test configurations discussion:

**Comment by artpol84** [comment]
Let's keep the summary on the test coverage discussion:

**Comment by gvallee** [comment]
@jjhursey @artpol84 As agreed during the call here is a description of the design of the tool I successfully implemented  for end-to-end testing in a different context than PMIx. It is only meant to give an feedback about what I think works and I did not really see any such tools available so far.

Major design characteristics:
- Support n dimensions regarding the configuration of the test and let the tool figure out all combination amongst all the dimensions and run the tests. For example, a dimension would be actual test (a script, a binary), another dimension ways to configure PMIx, another selection of components, another platform specific configurations. 
- Each dimension is specified via a configuration file: the tool is implementing how to perform a task for all dimensions but the actual definitions for each dimensions is through configuration files. For instance, a configuration file specifies which version of PMIx should be tested; another configuration file describes the arguments to use to configure PMix, etc... Having such configuration files aims at easing the understanding of what the experiments are supposed to be, let developers run tests for specific configurations. So the goal is not to ease the implementation of handling the configuration, compilation, installation, and execution of tests and their dependencies. Instead the goal is to separate such complexity from the actual definition of the tests that need to be executed.
- Results are saved in plain text file and ultimately stored in a separate Git repository. Addition and commits to this repository are not automatic, the user is in charge of checking the results (even if quickly) and manually add them. This process minimizes the risk of adding results with failures that are not acknowledged by developers.
- I always end up with supporting multiple arguments for the testing tool, simply to be able high-level intent regarding the test to run. A typical example, is to first support the execution of an easy pass/fail test and later on add a new test that will gather performance data. Because it is interesting to support both, I usually keep the default behavior as being the pass/fail test but add a command line argument to the testing tool to enable the execution of some specific test gather performance data.
- The tool does *not* interpret the results; separate tools can be developed to analyse the data and report problems. This is because the list of expected failures, expected successes, the accepted level of performance degradation vary over time.
- Internal functions of the tool are based on generic structures that capture each dimensions of the test as well as the system configuration and so on. The goal here is to minimize the need to change the internal APIs as more complex testing configurations are supported: there is only the need to had elements to existing structures. For example, standard data structures would be: system configuration (gathering all data such as path to binaries, and so on), experiment binary (path to the temporary directory where PMIx is compiled, directory where PMIx is installed, path to the test to execution, path to the result file). 
- Support resuming of testing: since we are dealing with n dimension, the execution of the tests is very quickly spawning many hours and sometimes days. Based on this, being able to resume tests is of paramount importance and fairly easy to do: (i) create the matrix of all the tests to run, (ii) create the matrix of all the results we have, and (iii) prune the matrix of tests to run based on the matrix of results we already have. Of course, optimizations are possible but that step is usually far quicker than running the actual tests.

Ultimately, this approach proved to let me have complex tests executed on multiple platforms, track problems with PASS/FAIL tests or even performance degradations. I usually use such an approach with actual software release but it is also possible to have periodic testing of code in a Git repository. My approach to do so is to have a small script that will periodically create a new configuration file with the current fingerprint of the branch of interest and then automatically start testing. Doing so, let me separate concerns (such a script is easy to write and should be fairly stable) and limit required modifications of the actual testing tool.

If interested, I can also describe how to structure the repository to store results. I can also give more details about this type of tools that I have been successfully developing over the year, just let me know what aspect you are interested in.

**Comment by rhc54** [comment]
Sorry I missed the discussion, but this sounds a lot like MTT (especially the Python client) minus the resumption of testing bullet. I'm wondering if it wouldn't be better to extend MTT as required since that is a platform (a) more familiar to the broader community and (b) under active support/development.

**Comment by gvallee** [comment]
Sounds fair to me. I do not know the new MTT very well, I did not know that we can have separate configuration files for all these aspects and store results outside of a database in a way that is flexible. Sorry for my lack of knowledge.

**Comment by rhc54** [comment]
Separate config files are not a problem. Anything they don't currently cover can easily be added as the Python client is very flexible (built on a plugin model). Storing outside a database is currently just a plain text file, but I don't consider that a major deal as we now have the db containerized for easy install. I don't think we want to start storing results in a Git repo, though, due to the eventual size constraints we would hit.

Harvesting things from your work and putting them into MTT sounds like the way to go.

**Comment by jjhursey** [comment]
MTT Running with PMIx and PRRTE+PMIX
 * https://github.com/pmix/pmix-tests/tree/master/intel
   - **Help needed**: Writing tests
 * https://github.com/open-mpi/mtt/
   - Plugins available for PMIx and PRRTE (Python Client)
 * Think about a matrix of client vs server component selection

**Comment by FaDee1** [comment]
ผู้รับโอน

**Comment by rhc54** [comment]
I think we can put this to rest - what has been done is likely to be it, at least for some time to come.
