### ISSUE TITLE
Version compatibility tables?

### ISSUE THREAD

**Issue by morrisonlevi** [openpmix/openpmix#1291]
I can't seem to find PMIx version compatibility tables, though I swear I've seen them before. Maybe we could get them into the README?
If I remember correctly, at least one piece of it is that something like starting from PMIx version 2.1, all released clients and servers are compatible. Is this correct? As far as you know, will this hold for PMIx 4 as well?

**Comment by rhc54** [comment]
You'll find a picture of it here: https://pmix.org/support/faq/how-does-pmix-work-with-containers/

> starting from PMIx version 2.1, all released clients and servers are compatible. Is this correct? 

Yes, that is correct.

There is every intention of it holding for v4 and beyond. We are investigating some potential issues at this time regarding the release branches and the level of cross-version support due to some limitations recently discovered in our test harness. We will provide an update on those matters once we have completed the investigation.

**Comment by morrisonlevi** [comment]
What versions are OpenMPI's internal PMIx compatible with? I imagine that is also somewhat version dependent.

**Comment by rhc54** [comment]
So the real question here is: what versions does each OMPI release carry internally? You can see the answer here: https://pmix.org/support/faq/which-environments-include-support-for-pmix/

**Comment by jjhursey** [comment]
Let us know if the link above does not answer your question or if a further clarification is needed. Thanks!
