### ISSUE TITLE
Issue with PMIx_Get for PMIX_RANK_UNDEF using jsrun

### ISSUE THREAD

**Issue by Mahdiehgh-osu** [openpmix/openpmix#1544]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

PMIx 3.1.3

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source/distribution tarball

### Please describe the system on which you are running

* Operating system/version: Linux/4.14.0-115.10.1.1chaos.ch6a.ppc64le
* Computer hardware: POWER9 CPU (Lassen Supercomputer)
* Network type: Infiniband ConnectX-5

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

I have attached a small program that uses PMIx_Put, PMIx_Commit, PMIx_Fence and PMIx_Get. I compiled and ran the code using the following commands:

```shell
shell$ gcc -o ./pmix -L/path-to-pmix-lib -I/path-to-pmix-include -lpmix ./pmix.c 
shell$ jsrun -r 2 ./pmix
```

I expect to have the following output:
val2->data.string=test_value_0
val2->data.string=test_value_1

However, the program got stuck in PMIx_Get. 

Note that I ran the same code with the following command on a system that has slurm workload manager and the output was as expected. 

```shell
shell$ srun --mpi=pmix -n 2 ./pmix
```
Please let me know if you have any idea what the issue might be.

Thanks,
Mahdieh
[pmix-code.txt](https://github.com/openpmix/openpmix/files/3842140/pmix-code.txt)

**Comment by dsikich** [comment]
Hi @Mahdiehgh-osu what version of JSM are you using?

**Comment by Mahdiehgh-osu** [comment]
Thanks for your reply. This is the jsm version:

```shell
shell$ jsrun --version
jsrun (Job Step Manager) 10.03.00.01rtm3 [Jun 11, 2019] built with PMIx 3.1.3rc1
```

**Comment by dsikich** [comment]
@Mahdiehgh-osu it looks like you built the version of PMIx you are linking with yourself when you launch with jsrun? Can you try running/launching with the PMIx library that was built with JSM on your system.

**Comment by rhc54** [comment]
I suspect that the JSM machine doesn't know how to process values for a rank of ```PMIX_RANK_UNDEF```. Since it is a blocking "get", it will hang waiting for the value to be resolved. 

You might check to see what PMIx version was used on the Slurm machine. Might be that the version used there can handle it better.

To be technically correct, you should use either your own rank (since you are the one who posted the value), or just pass a ```NULL``` for the first argument to "get" since you are working directly with the PMIx interfaces. The "undef" rank is only used when we are working thru the PMI-1/2 wrappers as the user doesn't know who posted the data.

**Comment by Mahdiehgh-osu** [comment]
Thanks for your prompt reply and guidance.

@dsikich We used the same PMIx library that was used to build JSM.

@rhc54 We tried two different PMIx versions (PMIx-2.2.3 and PMIx-3.1.4) on Slurm machine and they both worked fine.

Our intention is to get the data from any rank that has the specified key, it can be my own rank or any other rank. We tried NULL and PMIX_RANK_WILDCARD for the first argument of PMIx_Get but non of them worked.
 
For now, we get around the problem by searching through all the ranks in the namespace to find the rank that matches the specified key. But let us know if you had a better solution. 

Thanks,
Mahdieh

**Comment by jjhursey** [comment]
FYI @dsolt

**Comment by jjhursey** [comment]
@Mahdiehgh-osu I noticed one error in your program. The `pmix_proc_t` structure's `nspace` field is not initialized. This was causing the test to hang with `mpirun` from Open MPI as well.

I made the following change to your program (added the `memcpy`):
```
        # Copy in the myproc to pick up the namespace string
        memcpy(&proc, &myproc, sizeof(myproc));
        proc.rank = PMIX_RANK_UNDEF;
        rc = PMIx_Get(&proc, key, NULL, 0, &val2);
```

Using that and the latest release of JSM this test passes.
```
[jjhursey@c712f6n01 take2] gcc -o ./pmix-example -L$SMPI_ROOT/lib -I$SMPI_ROOT/include -lpmix ./pmix-example.c
[jjhursey@c712f6n01 take2] jsrun --version
jsrun (Job Step Manager) 10.03.01.00rtm5 [Nov 14, 2019] built with PMIx 3.1.4

Report bugs to http://www-03.ibm.com/systems/spectrum-computing/support.html
[jjhursey@c712f6n01 take2] jsrun -r 2 ./pmix-example
val2->data.string=test_value_1
val2->data.string=test_value_3
val2->data.string=test_value_0
val2->data.string=test_value_2
```

Using the JSM release that you cited (`10.03.00.01rtm3 [Jun 11, 2019] built with PMIx 3.1.3rc1`) it does hang for me (as does `mpirun`).

The biggest difference between these two is the inclusion of the fix for Issue #1278 which is likely the source of the fix. The latest JSM release includes this fix since it was released with 3.1.4.

**Comment by jjhursey** [comment]
Thanks for the additional use case for `PMIX_RANK_UNDEF`. Currently, it is not well optimized in OpenPMIx since most keys are associated with a specific rank. As such the handling of `PMIX_RANK_UNDEF` is not handled by the shared memory key/value store (`dstore`), but by the `hash` component. Depending on your application, and the number of these keys you use you might see the slight performance impact. This optimization may be related to Issue #1396 for `dstore`.

One alternative is to always assign such keys to `rank=0` so you have a rendezvous point for them, and don't have to search all of the ranks for them.

**Comment by Mahdiehgh-osu** [comment]
@jjhursey Thanks for the information. Good to know that the issue is fixed in latest release.

**Comment by jjhursey** [comment]
I'm going to close this issue as completed. Feel free to re-open if you believe there to be more work to do. Thanks!
