### ISSUE TITLE
Compiler warnings in dstore components

### ISSUE THREAD

**Issue by rhc54** [openpmix/openpmix#1594]
I'm seeing these warnings emitted when doing an optimized build:
```text
gds_ds20_file.c: In function 'pmix_ds20_put_key':
gds_ds20_file.c:70:5: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   70 |     strncpy((char *)addr + sizeof(size_t),                  \
      |     ^~~~~~~
gds_ds20_file.c:116:5: note: in expansion of macro 'ESH_PUT_KEY_V20'
  116 |     ESH_PUT_KEY_V20(addr, key, buf, size);
      |     ^~~~~~~~~~~~~~~
gds_ds20_file.c:32:24: note: length computed here
   32 |     size_t kname_len = strlen(key) + 1;                     \
      |                        ^~~~~~~~~~~
gds_ds20_file.c:71:18: note: in expansion of macro 'ESH_KNAME_LEN_V20'
   71 |             key, ESH_KNAME_LEN_V20(key));                   \
      |                  ^~~~~~~~~~~~~~~~~
gds_ds20_file.c:116:5: note: in expansion of macro 'ESH_PUT_KEY_V20'
  116 |     ESH_PUT_KEY_V20(addr, key, buf, size);
      |     ^~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:190,
                 from ../../../../include/pmix_common.h:59,
                 from gds_ds12_file.c:12:
gds_ds12_file.c: In function 'pmix_ds12_put_key':
gds_ds12_file.c:78:5: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   78 |     strncpy((char *)addr, key, ESH_KNAME_LEN_V12(key));     \
      |     ^~~~~~~
gds_ds12_file.c:127:5: note: in expansion of macro 'ESH_PUT_KEY_V12'
  127 |     ESH_PUT_KEY_V12(addr, key, buf, size);
      |     ^~~~~~~~~~~~~~~
gds_ds12_file.c:52:18: note: length computed here
   52 |     size_t len = strlen((char*)key) + 1;                    \
      |                  ^~~~~~~~~~~~~~~~~~
gds_ds12_file.c:78:32: note: in expansion of macro 'ESH_KNAME_LEN_V12'
   78 |     strncpy((char *)addr, key, ESH_KNAME_LEN_V12(key));     \
      |                                ^~~~~~~~~~~~~~~~~
gds_ds12_file.c:127:5: note: in expansion of macro 'ESH_PUT_KEY_V12'
  127 |     ESH_PUT_KEY_V12(addr, key, buf, size);
      |     ^~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:190,
                 from ../../../../include/pmix_common.h:59,
                 from gds_ds21_file.c:13:
gds_ds21_file.c: In function 'pmix_ds21_put_key':
gds_ds21_file.c:168:5: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  168 |     strncpy(addr_ch + 2 * sizeof(size_t), key, ESH_KNAME_LEN_V21(key));
      |     ^~~~~~~
gds_ds21_file.c:43:6: note: length computed here
   43 |     (strlen(key) + 1)
      |      ^~~~~~~~~~~
gds_ds21_file.c:168:48: note: in expansion of macro 'ESH_KNAME_LEN_V21'
  168 |     strncpy(addr_ch + 2 * sizeof(size_t), key, ESH_KNAME_LEN_V21(key));
```
These look valid to me - one shouldn't limit a strncpy by the size of the input string, but rather by the size of the target.

@artpol84 @karasevb Can you please address these?

**Comment by artpol84** [comment]
@rhc54, we will

**Comment by artpol84** [comment]
So I checked this and I think that we should be OK from the correctness standpoint.
* There is only one place where we put the key name [[link](https://github.com/openpmix/openpmix/blob/master/src/mca/common/dstore/dstore_base.c#L1153)]. For this case we have several checks that 
  * Ensure that this particular key + required meta information may potentially fit single segment [[link](https://github.com/openpmix/openpmix/blob/master/src/mca/common/dstore/dstore_base.c#L1111)]
  * If above is true, we check if the key can fit the current segment: [link](https://github.com/openpmix/openpmix/blob/master/src/mca/common/dstore/dstore_base.c#L1129)], if not - we allocate a new one that will fit 100% because of the first check.

We also have 2 service keys: "invalidated" and "extension slot", that are only used in ds12 and we use flags incorporated in the key length for ds21. For those keys, we have a way to reserve space in advance.

Compiler obviously can't track such complex dependencies. 

However, I agree that the in-pace check would look more readable. So we can pass an additional argument to the put function to identify remaining space in the segment. In this way, the put function will be able to verify that what it is doing is correct in case the logic above is busted for some reason.

**Comment by pkovacs** [comment]
I note the major soname bump with 3.1.5rc1 from `libpmix.so.2` to `libpmix.so.3 `.  You're signalling a significant abi change with that bump -- was that the intent for this bugfix release?  It's more work downstream, as an announcement has to be made so that all pmix client packages can be rebuilt.

**Comment by rhc54** [comment]
Are you talking from v2.x? If so, then yes - there is a significant change. If it is relative to v3.1.4, then that is an error.

**Comment by pkovacs** [comment]
@rhc54 3.1.4 is libpmix.so.2, but 3.1.5rc1 is .so.3.

**Comment by rhc54** [comment]
okay, let's take this over to a more appropriate issue as this has nothing to do with the dstore compilation warnings.

**Comment by artpol84** [comment]
@pkovacs  @rhc54 
Was https://github.com/openpmix/openpmix/issues/1594#issuecomment-579947077 sufficient?
Can we close this one?

**Comment by rhc54** [comment]
No, this issue got sidetracked - the original warnings are still there

**Comment by artpol84** [comment]
ahh I see.
Basically what I said in https://github.com/openpmix/openpmix/issues/1594#issuecomment-579947077 is that those warnings are false positives.
But we can/should restructure the code so for the compiler it'll obvious.compiler

**Comment by rhc54** [comment]
No longer relevant
