### ISSUE TITLE
PMIx_tool_connect_to_server missing proc output

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#1801]
`PMIx_tool_connect_to_server` takes a `proc` output argument as the first parameter, but does not fill it in if a non-NULL pointer is provided.

```
 * NOTE: PMIx does not currently support on-the-fly changes to the tool's
 * identifier. Thus, the new server must be under the same nspace manager
 * (e.g., host RM) as the prior server so that the original nspace remains
 * a unique assignment. The proc parameter is included here for obsolence
 * protection in case this constraint is someday removed. Meantime, the
 * proc parameter will be filled with the tool's existing nspace/rank, and
 * the caller is welcome to pass _NULL_ in that location
 */
PMIX_EXPORT pmix_status_t PMIx_tool_connect_to_server(pmix_proc_t *proc,
                                                      pmix_info_t info[], size_t ninfo);
```

The scenario where we were experimenting with this interface is in an indirect debugger launch scenario. So we would either call `PMIx_Spawn` or fork/exec the prterun/mpirun launcher. Then use `PMIx_tool_connect_to_server` to connect to the launcher process. We need the `proc` structure filled out with the process information of prterun/mpirun so we can then use that information to register for events.

This seems to be a supported type of operation. Should we update the Note in the API?

**Comment by jjhursey** [comment]
IBM team came up with this quick patch, but we are not 100% sure it's correct

```diff
index dcb7da3e..33178922 100644
--- a/src/tool/pmix_tool.c
+++ b/src/tool/pmix_tool.c
@@ -1485,6 +1485,12 @@ pmix_status_t PMIx_tool_connect_to_server(pmix_proc_t *proc,
         return rc;
     }
 
+    // Fill in the proc structure if provided
+    if( NULL != proc ) {
+        strcpy(proc->nspace, pmix_client_globals.myserver->nptr->nspace);
+        proc->rank = 0;
+    }
+
     /* once that activity has all completed, then stop the new progress thread */
     pmix_progress_thread_stop("reconnect");
     pmix_progress_thread_finalize("reconnect");
```

**Comment by rhc54** [comment]
Took me a little bit to register what you were doing, but no - that is not a correct patch. The `PMIx_tool_connect_to_server` function should fill the proc struct in with its own nspace and rank, not that of the server to which it connected. If it isn't doing that, then I'll fix it.

The MPIR shim is doing this correctly, if you want to look at it for an example. When you call `PMIx_Spawn`, the spawn function returns the namespace of the spawned process - in this case, it is the namespace of the launcher. You know the rank is zero since only one process is being started.

Thus, as the MPIR shim does, once you return from `PMIx_Spawn` you know the namespace of the launcher and can register for events against it. You don't need to know the namespace/rank of any server the launcher might be attached to - you only need to know the namespace of the launcher itself.

**Comment by jjhursey** [comment]
Thanks for the fix. That makes sense.

Is there an easy way (I need to look) to access the process id/namespace of the server that we just connected to? For example, to send an event to that server.

**Comment by rhc54** [comment]
Assuming the server supports it, you could do a `PMIx_Query` of `PMIX_SERVER_NSPACE` and `PMIX_SERVER_RANK`. It would probably be better if we just updated the PMIx library so that one could do a `PMIx_Get` on those values since the local library already has it. Stand by.

**Comment by rhc54** [comment]
Should be addressed in https://github.com/openpmix/openpmix/pull/1809
