### ISSUE TITLE
run_tests0{2,4}.pl: fails on armv7hl (Fedora 33)

### ISSUE THREAD

**Issue by junghans** [openpmix/openpmix#1828]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
pmix-3.1.5

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
During rpm build for Fedora 33

### Please describe the system on which you are running

* Operating system/version: Fedora 33 (Rawhide)
* Computer hardware: VM
* Network type: ?

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

Upstream build: https://koji.fedoraproject.org/koji/taskinfo?taskID=48673448 & https://bugzilla.redhat.com/show_bug.cgi?id=1865241

arm7hl build log [here](https://github.com/openpmix/openpmix/files/5025152/build_arm.log.txt)

**Comment by junghans** [comment]
And here is the build log with `PMIX_DEBUG=10`
[build_debug10.log.txt](https://github.com/openpmix/openpmix/files/5025321/build_debug10.log.txt)

**Comment by rhc54** [comment]
Thanks! Just for clarity: was this done from tarball or from GitHub clone?

**Comment by rhc54** [comment]
I'm asking because the head of the v3.1.5 branch is slightly ahead of v3.1.5 release as we are prepping for a v3.1.6 in the next month

**Comment by junghans** [comment]
The rpm is using https://github.com/pmix/pmix/releases/download/v3.1.5/pmix-3.1.5.tar.bz2

**Comment by rhc54** [comment]
Hmmm...I was afraid of this. I cannot replicate on the machines available to me, which means this might be something ARM-specific. Afraid I'm not sure where to go from here.

@ggouaillardet @hppritcha Do you have access to something like this? It's an arm7hl. All my machines are Intel-based, I'm afraid.

**Comment by junghans** [comment]
If you want me to do any debugging in the build please let me know.

**Comment by pkovacs** [comment]
I got almost immediate feedback from the mpi people when I excluded a armv7hl as a wrokaround in Fedora.  I am re-adding it but excluding the tests, i.e. the `make check` is omitted on armv7hl.  This is almost certainly a bad thing to do since the checks are revealing an issue somewhere... we should find the problem and fix it.

My feeling is that there might be some 64-bit assumptions that break on arm's 32-bit architecture.  Just grepping casually, look below, for example (there are many others) -- these c-style casts are lossy.

```
mca/bfrops/v20/print.c:                      prefx, (long)src->data.int64);
mca/bfrops/v20/print.c:                      prefx, (unsigned long)src->data.uint64);
```

**Comment by rhc54** [comment]
Such casts are often done in print statements for debugging purposes, so I doubt that is the issue here. What we need is access to an appropriate machine as none of the members of the developer community use ARM. Anyone know where we could find one? I might be able to try my little Raspberry PI, but I haven't turned it on in months - would take me a bit to bring it back online.

**Comment by pkovacs** [comment]
I think I may have found the problem.  I spun up a Fedora armv7hl vm under kvm/qemu and built pmix (a painfully slow overall process).  The first few tests failed initially, as reported above.  Seeing how slow the vm was and noting that there is a hard timeout of 30 seconds given to each test after which the timeout wrapper issues a kill signal,  I patched our rpm spec to give the tests much more time to finish:

```
# pmix.spec
echo give tests more time to complete on slower build vms
find test -name run_tests\*.pl\* -exec \
sed -i 's/preserve-status -k 35 30/preserve-status -k 305 300/' {} \;
```

My scratch build succeeded on Fedora's build vm given the extra time.  See [build.log](https://kojipkgs.fedoraproject.org//work/tasks/6165/48856165/build.log).

The upstream code is in `test/test/run_tests.pl.in` in the two `$timeout_cmd` statements. The tests are given 30 secs
and I simply bumped them up to 300 seconds.

**Comment by rhc54** [comment]
Woohoo! Thanks @pkovacs !  @junghans - can you please let us know if that solves the problem for you too?

**Comment by pkovacs** [comment]
I ran another pmix scratch build for all six Fedora architectures using the 300 sec timeout and all arches passed: [scratch build](https://koji.fedoraproject.org/koji/taskinfo?taskID=48890512).  I'm satisfied at this point, so I committed the rpm spec change above to Fedora's rawhide repo (master) and rebuilt the official rawhide release, again all arches passed: [official rawhide build](https://koji.fedoraproject.org/koji/taskinfo?taskID=48891140).

@rhc54 If you do change the timing, I will remove my patch in favor of your code.  I suppose you might consider making the timeout a configure item -- up to you of course.

**Comment by junghans** [comment]
@pkovacs thanks for the investigation.

**Comment by rhc54** [comment]
@junghans @pkovacs Obviously, I cannot bring the fix back to the v3.1.5 release, but I can do a v3.1.6 release that contains it. There are a few things in that branch, including removal of an unnecessary "warning" message that appears at least on Mac, so I could justify it. Or you can use your own patch if you are satisfied otherwise.

Let me know which you would prefer. Would take about a week to generate the release.

**Comment by junghans** [comment]
Just leave it for the upcoming 3.1.6 release, we have patched the rpm already, so there is no need to backport.

**Comment by pkovacs** [comment]
Yep, 3.1.6 is fine. I receive your automatic email, Ralph, when you release so I'll have it in Fedora within hours probably.  Meantime the sed replace patch is added just in case anyone triggers a rebuild -- sometimes the Fedora gods come in and do a "mass rebuild" when deep structural dependencies change, which was what triggered this problem.  All good now.
