### ISSUE TITLE
PMIX_PROC_INFO defined as integer instead of "pmix.proc.info"

### ISSUE THREAD

**Issue by dsolt** [openpmix/openpmix#2225]
## Background information

Trying to use a PMIx_Get of PMIX_PROC_INFO but compiler is complaining that PMIX_PROC_INFO is defined as the integer 38 and is not a string:

<somepath>/include/pmix_common.h:1333:41: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
 #define PMIX_PROC_INFO                  38
                                         ^~
foo.cpp:84:21: note: in expansion of macro 'PMIX_PROC_INFO'
     PMIx_Get(&proc, PMIX_PROC_INFO, NULL, 0, &val);

It seems like this is a standards issue because PMIX_PROC_INFO is defined in the standard to be both a key and as a PMIx type.

### What version of the PMIx Reference Library are you using? 

4.1

### Describe how PMIx was installed 

git clone

**Comment by rhc54** [comment]
Checked all the way back into the v1.2 series, and `PMIX_PROC_INFO` has always been a PMIx data type (i.e., integer). What info were you trying to retrieve?

**Comment by dsolt** [comment]
I see my use of PMIX_PROC_INFO isn't really a good example as you probably wouldn't do a PMIX_Get on PMIX_PROC_INFO as the key, but you might use PMIX_PROC_INFO as an attribute in a PMIx_Get.   That explains why others are not seeing this issue, but I think it is a standards issue that needs to be resolved there first and then openpmix can fix accordingly?  Thoughts?

**Comment by rhc54** [comment]
You'd at least need to correct the standard - we can then figure out if something more needs to be done.

If I'm grokking this correctly, I suspect the problem lies in someone wanting to create a corollary to the `PMIX_NODE_INFO` (and friends) attribute that stipulates "I want the node-level info for the specified key". This is needed when a key is shared across multiple levels (node, app, job, session). The proc-level version doesn't exist because it isn't needed - since `PMIx_Get` takes a proc ID as an argument, the info it returns will _always_ be the proc-level info unless you stipulate otherwise. So I suspect simply removing the attribute from the standard, perhaps including the above explanation as to why it isn't needed, should suffice.

**Comment by dsolt** [comment]
Agreed.   Hunting it down further, the standard says:

**Comment by dsolt** [comment]
Up to you if we close this issue here, but I think it will be an easy standards change to fix this up.  I'll drive it over there :)

**Comment by rhc54** [comment]
Yeah, I probably screwed up and added it for the stated reason. Just delete it. I'll close this.
