### ISSUE TITLE
`pkg-config` info for embedded pmix

### ISSUE THREAD

**Issue by karasevb** [openpmix/openpmix#2403]
## Background information

Following PR https://github.com/openpmix/openpmix/pull/1939 it disables the required libs (libevent, hwloc) in `pmix.pc` file when PMIx is built as embedded. We can be faced with the backside, when somebody has installed OMPI (with embedded libs libevent, hwloc), and trying to rely on the `pkg-config pmix` output where absents the info of libevent and hwloc (even though they are embedded) lib paths. That leads to some confusion.

-----------------------------

## Details of the problem

The question is in the correctness to rely on `pkg-config` for embedded pmix, correctness to use embedded pmix lib on somewhere else?

**Comment by rhc54** [comment]
I don't know anything about `pkg-config` as someone else added that capability. I note that @bwbarrett recently changed the `.pc` file, so perhaps he has some suggestions here?

**Comment by bwbarrett** [comment]
@karasevb what branch/configuration are you trying to use?  I think there are two cases:

1) OMPI 4.x and earlier (and related branches): libpmix is going to be sucked into libopen-pal.so, so we shouldn't be installing a pmix.pc file at all (because you can't use it, because there's no libpmix.so).

2) OMPI 5.0 and later: libpmix is installed standalone, but so are hwloc and libevent (even if the OMPI-packaged versions are used).  In this case, I think the pmix.pc file is right; you do need hwloc and libevent to link PMIx.

There is a slight problem in everything I said, which is that in OMPI 5.0 (and the 4.1/4.2 openpmix branches), libevent and hwloc are listed as requirements, when they should be private requirements.  I fixed this on openpmix master (https://github.com/openpmix/openpmix/commit/e2102a569873e476ee41e634382ac3c275b95932), but have neglected to file PRs to backport those changes.

**Comment by rhc54** [comment]
Believe this has been fixed - please reopen if you continue to have a problem
