### ISSUE TITLE
How does the singleton concept work (server library)?

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2596]
### What version of the PMIx Reference Library are you using?

4.1.2

### Describe how PMIx was installed

from a source tarball

-----------------------------

## Question

I am trying to implement singleton functionality in a RM using the OpenPMIx server library to provide PMIx.

From the source code I could read, that if there is no PMIx environment found, a namespace 'singleton.$hostname.$pid' is set up implicitly and then `pmix_tool_init_info()` is called. It seemed to me as it should look like a tool connecting to the server.

So I tried to call `PMIx_server_init()` with `PMIX_SERVER_TOOL_SUPPORT` info set to `true` and looked for a call of the function registered to `pmix_server_module_t.tool_connected` during running the pmix_client example program without PMIx environment. Unfortunately I could observe nothing on the server side and the client failed like this:
```shell
Client 16743: Running
Client ns singleton.node02.16743 rank 0: PMIx_Init failed: UNREACHABLE
```

Now my first question is: "Is my assumption right so far and I do now need to debug by the tool rendezvous mechanism is not working?"

If I am right so far, the second specific question is: "If the client has TMPDIR in the environment set to the same directory as passed to the server with the `PMIX_SERVER_TMPDIR` attribute (and this is set rw for both), the rendezvous should work in general? Are there further constraints that I am missing?

If I am on the wrong path, I would be thankful for an explanation how this is intended to work or a hint on were I can find information about.

**Comment by rhc54** [comment]
Hmmm...I think you might be a little confused. Singleton mode means that the client is not going to attempt to connect to a server because it doesn't know about any servers. Thus, it will return `UNREACHABLE` to indicate that it is alive, but cannot connect to a server. MPI libraries like OMPI use this as an indicator that the app is running as an MPI "singleton".

At some later point, the client application can re-call `PMIx_Init` and pass down server connection information if it has obtained that info from some other means. The library will attempt to connect to the indicated server at that time. The server information must be passed in the `pmix_info_t` array in the `PMIx_Init` call.

I do have an extension sitting on a branch where I allow client apps to search for server contact files and then initiate a connection just like a tool. I haven't committed it because it feels a little odd - the only difference between a "client" and a "tool" is precisely that search/connect mechanism. So if you want your app to go out and find a server, then the app should call `PMIx_tool_init` instead of `PMIx_Init`. If I do bring it in, it would be as an attribute to `PMIx_Init` that indicates "if you don't see server info in the environment, then please search for server contact files".

**Comment by krempel-pt** [comment]
Ok, great. Until I had a look into the source code of `PMIx_Init()` I had been expected exactly the strategy that you described.

I think I understood the concept now, but I have some questions for curiosity:

What confused me, was that near the comment `/* attempt to connect to a server */` if the call of `pmix_ptl.connect_to_peer()` failed `pmix_tool_init_info()` is called. What is the meaning of that call?

At the same place, a macro `PMIX_PEER_IS_SINGLETON()` is used, what does that mean? How can a server be a singleton?

Earlier in `PMIx_Init()` if no `PMIX_NAMESPACE` is found in the environment, this implicit namespace name `"singleton.%s.%lu", pmix_globals.hostname, (unsigned long) pid` is generated and that name later returned to the caller of `PMIx_Init()`. What is this meant for?

Thanks for taking the time.

**Comment by rhc54** [comment]
> What confused me, was that near the comment /* attempt to connect to a server */ if the call of pmix_ptl.connect_to_peer() failed pmix_tool_init_info() is called. What is the meaning of that call?

Even a singleton expects to be able to retrieve (via `PMIx_Get`) a certain set of information. The `pmix_tool_init_info` function simply locally stores default values of that information appropriate for a job of size=1.

> At the same place, a macro PMIX_PEER_IS_SINGLETON() is used, what does that mean? How can a server be a singleton?

A server is never a singleton - but you are looking in the _client_ init function (and not the server one). We are checking to see if this client started as a singleton (which is what that macro checks), but has connected to a server (which is the code path in that "if-else" chain). This may be a lingering code path as I don't see how that can happen - or it may be that something "leaked" from my branch at some point.

> Earlier in PMIx_Init() if no PMIX_NAMESPACE is found in the environment, this implicit namespace name "singleton.%s.%lu", pmix_globals.hostname, (unsigned long) pid is generated and that name later returned to the caller of PMIx_Init(). What is this meant for?

Even a singleton needs to have a unique identifier for interacting with its PMIx client library. Since there is no server to provide one, the client library generates something hopefully unique.

**Comment by krempel-pt** [comment]
Many thanks for the explanations, Ralph.
