### ISSUE TITLE
Is pcompress/zlib functional?

### ISSUE THREAD

**Issue by stoeckmann** [openpmix/openpmix#2626]
I came across the pcompress/zlib implementation while inspecting usages of `deflateBound` in different open source projects.

It seems to me that zlib compression is not performed due to invalid API usage. If it would be actually used, the decompression of strings has a good chance to fail with out of boundary access.

The pull request can be seen here: https://github.com/openpmix/openpmix/pull/2625

Unfortunately I have no proof of concept for these changes. What I did was:
- Remove the checks in `zlib_compress` to always compress (regardless of lower limit and if deflation actually increases in size)
- Add debug printf statements
- Run `prte` and `prun ls` on the same system

With these changes, compression occurs. But decompression fails. It claims that 800 MB sized strings would be transmitted, which must be wrong. Maybe the length conversation is off somewhere.

Can you help me with this one and let me know if ...
- ... environment variables can be set to override these limits and show more debug information
- ... small programs can be written which simply exchange zlib compressed strings
- ... and how to run them locally?

Thanks in advance!

**Comment by rhc54** [comment]
Hmmm...I'm not sure those changes are actually correct - or at least, they don't quite fit with the documentation I've seen. It would take a bit to refresh my memory and dig through it more.

Note that we don't really compress strings in PRRTE, so that pcompress string API doesn't see much use there. Likewise, it takes a really large job to get any compression to occur. However, we do have a check that runs to ensure it is working correctly, and so far we aren't seeing any errors.

That doesn't mean the code is correct, of course - we may just be lucky.

I'm rather tied up with other things right now, so this may wait a bit. Meantime, I can try to post some questions and suggestions on the PR.
