### ISSUE TITLE
New release 4.1.2+ coming?

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2647]
### What version of the PMIx Reference Library are you using?
4.1.2 and current master

### Describe how PMIx was installed
`../configure --enable-debug --prefix=... CFLAGS=-DHAVE_SYSLOG --with-libevent=/usr; make -j8; make install`

### Please describe the system on which you are running

* Operating system/version: Fedora 36 and Rocky 8.5
* Computer hardware: qemu vm x86
* Network type: virtual ethernet

-----------------------------

## Details of the problem

With the pmix 4.1.2 release I do see some problems when testing the dmodex host server implementation of our resource manager ParaStation Management.

Doing the exact same testing with the current master of openpmix, everything is working as expected. This brings me to the conclusion, that there have been made some improvements in this area and I doubt that it's worth to investigate the problems with 4.1.2 likely to just find problems already known and solved. But since this is to be used on production systems, it rises the question when it is planed to get the improvements in a new released version?

Thanks a lot.

**Comment by rhc54** [comment]
I am still wrestling with what to do with the v4.1 series. If I perform all the backports required to make it work correctly with the upcoming PRRTE v3.0 release, it winds up looking exactly like the upcoming v4.2 release. The problem is that it requires more than just bug fixes - there are quite a few functional changes and new definitions also required by PRRTE v3.0.

I had been doing many of those updates, but stopped when I began to realize that v4.1.2 and v4.2 were becoming essentially identical. I'm not entirely sure of the correct solution, but am increasingly leaning towards reverting v4.1 back to the v4.1.1 marker and holding it there, perhaps adding a few true bug fixes for a final v4.1.2.

This means that PRRTE v3.0 will require PMIx v4.2.0 or above, but I don't think that will be too big of an issue (though I'm willing to listen if it is).

**Comment by krempel-pt** [comment]
I guess you mean 4.1.3 when writing 4.1.2 and your consideration is to let the 4.1 series end with the (already released) 4.1.2, right?

For my case, it doesn't matter whether it is 4.1.x or 4.2.x. A 4.2.0 release basing on the current master would be perfectly fine. So perhaps I did not choose the perfect headline for this issue. The actual question is for any release containing the latest enhancements from the master branch. Can you already tell a time frame for this to be release ready?

**Comment by rhc54** [comment]
Sorry - I got confused by the 4.1.2 reference. I will release a 4.1.3 that has some bug fixes (will first reset the 4.1 branch to 4.1.2 and work up from there). Hope to do that in Aug. I also expect to release 4.2.0 in Aug.

So far as I know, there remain only one or two bugs to be fixed before 4.2.0 release. I'm working on them now, so barring some unexpected problem we should hold to that schedule.

**Comment by krempel-pt** [comment]
Ok, great, thanks.
