### ISSUE TITLE
Calling PMIx client APIs like PMIx_Get or PMIx_Put in registered event handlers.

### ISSUE THREAD

**Issue by darbyShaw** [openpmix/openpmix#2654]
### What version of the PMIx Reference Library are you using? 
git master @ 7f458b5fc0ad5cc10d82f534cdd4ba9f4aa4cce5

### Describe how PMIx was installed 
git clone

### Please describe the system on which you are running

* Operating system/version: Oracle Linux Server release 8.6
* Computer hardware: x86_64
* Network type:

-----------------------------

## Details of the problem

In order to create and exchange endpoint context/information on demand or on need basis I implemented the following in an application:
1. If a process wants to connect to a peer on another node, it creates an endpoint for the remote process and stores it at its local PMIx server using PMIx_Put. It then notifies the remote peer using a PMIx_Notify_event with a connection event. The local process then waits for the remote end to post its endpoint information using PMIx_Get which calls the dmodex function and blocks till information is available on the remote side.
2. The remote process on receiving the connect event, posts its endpoint information for the notifying source using PMIx_Put and collects the posted endpoint information from the other side using  PMIx_Get  that does dmodex.

On the remote process, since the event handler is still a callback function of an event of the client event base, we cannot perform PMIx_Put  or PMIx_Get in the handler (because these thread shift to the event loop thread)  but instead need to spawn a thread for these operations from the event handler and return immediately from the event handler.

If I have understood things correctly, is there a better way to be able to call  PMIx_Put  or PMIx_Get in the event handler without having to spawn and track a new thread in the client application ? 

Thank you very much in advance.

**Comment by rhc54** [comment]
I would suggest simplifying that exchange a bit. If you are going to use an event to notify the remote side that you want to communicate with them, then you might as well send the endpoint as part of the event payload. The remote end can then to the same to return its corresponding endpt.

This avoids the use of blocking APIs in event handlers. You are allowed to call `PMIx_Notify_event` from within a handler. So basically,  you register an event handler for receiving connection info from remote procs. You'll need some non-PMIx storage for temporarily caching the returned info since (as you noted) you cannot call `PMIx_Put` from inside the handler. However, if you are going to use the connection info somehow, you'd need to have a place to store it in your app anyway, yes?

Inside that event handler, you would create a corresponding local endpt and pass it in the event info for `PMIx_Notify_event` to return it to the remote proc. Use the directives to target the specific remote proc you are connecting to.

You'll need some way of knowing when the exchange is complete. Checkout the example in `examples/jctrl.c` to see how we use pthread methods for doing so without creating additional threads.

That should be all you require, and does not involve adding a thread in the client. Note that this all depends on the host environment supporting the event notification system. Hope that helps.
