### ISSUE TITLE
PMIX_INFO_CREATE(m, 0) not supported

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#2656]
### What version of the PMIx Reference Library are you using?
master branch

-----------------------------

## Details of the problem

The macro `PMIX_INFO_CREATE` does either not support `n=0` that is not forbidden by the standard at least or it relies on `calloc(0)` to return `NULL` which is not necessarily the case according to the manpage:

> The  calloc() function allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.  The memory is set to zero.  If nmemb or size is 0, then calloc() returns either NULL, or a unique pointer value that can later be successfully passed to free(). 

```
#define PMIX_INFO_CREATE(m, n)                                  \
    do {                                                        \
        pmix_info_t *_i;                                        \
        (m) = (pmix_info_t*)pmix_calloc((n), sizeof(pmix_info_t));   \
	    if (NULL != (m)) {                                      \
            _i = (pmix_info_t*)(m);                             \
            _i[(n)-1].flags = PMIX_INFO_ARRAY_END;              \
        }                                                       \
    } while (0)
```

I would have proposed to change it to 
```
        (m) = (n) ? (pmix_info_t*)pmix_calloc((n), sizeof(pmix_info_t)) : NULL;   \
```
but I an not certain enough about all implications to directly open a pull request in this case.

In my opinion, supporting `n=0` makes sense, since it enables using the macro like that and so ease things:
```
size_t ninfo = 0;
pmix_info_t *info;

if (cond1) ninfo++;
if (cond2) ninfo++;

PMIX_INFO_CREATE(info, ninfo);

size_t i = 0;
if (cond1) PMIX_INFO_LOAD(&info[i], ...);
if (cond2) PMIX_INFO_LOAD(&info[i], ...);

PMIx_Whatever(...,info, ninfo, ...);

PMIX_INFO_FREE(info, ninfo);
```

**Comment by rhc54** [comment]
Hmmm...I would suggest caution about assuming that what is not explicitly forbidden in the Standard must be supported. The document wasn't written with that intention. I would instead suggest reading it the opposite way - that which is not explicitly allowed in the Standard may or (more likely case) may not be supported.

That said, I have no problem putting a check for "n=0" in the macro. I personally avoid the use of "calloc" because it has such ambiguities in it, so that is easily fixed.

However, note that we provided the `PMIx_Info_list_xxx` functions specifically to support the case you show. You might want to look at them.

**Comment by krempel-pt** [comment]
> However, note that we provided the `PMIx_Info_list_xxx` functions specifically to support the case you show. You might want to look at them.

I will, thanks for the hint.
