### ISSUE TITLE
llvm doesn't like string literals exceeding 4095 bytes - and OpenPMix may have such literals

### ISSUE THREAD

**Issue by hppritcha** [openpmix/openpmix#2784]
I'm observing that some of the string literals defined as part of the OpenPMIx configure can lead to string literals exceeding ISO C99 limit of 4095 bytes which leads to compilation failures with the default PMIx configure options when using llvm (at least 14 or newer):
```
support.c:1261:59: error: string literal of length 5592 exceeds ma
             ximum length 4095 that ISO C99 compilers are required to support [
             -Werror,-Woverlength-strings]
```
I think this is happening when ```pmix_git_repo_build``` configure variable evaluates to yes.

**Comment by rhc54** [comment]
Hmmm...written by Jeff.

@jsquyres Do you have any suggestions here? I should think this is something you will hit in OMPI as well?

**Comment by rhc54** [comment]
Hmmm...I see a couple of options here, listed in order of likelihood of happening:

1. we wait for OMPI to fix it on their side and then just copy it. You'll hit this too (I suspect @hppritcha will be opening an issue there shortly), so might as well see your solution
2. we just dump the configure line storage since it only gets used for `pmix_info`
3. disable pickiness on these overly picky compilers
4. some other solution

The likelihood of my using my retirement time on this problem is very low 😄

**Comment by rhc54** [comment]
I believe (3) or (2) look like the best option - I don't see anyone particularly motivated to develop a solution. Can reopen should a solution appear or someone volunteers to resolve it.
