### ISSUE TITLE
Odd include files installed

### ISSUE THREAD

**Issue by opoplawski** [openpmix/openpmix#3021]
## Background information

I'm looking at updating the Fedora pmix package from 4.1.2 to 4.2.3 and noticing a bunch of new include files installed:

```
/usr/include/pmix/src:
class  client  common  event  hwloc  include  mca  runtime  server  threads  tool  util
```

These seem like internal headers - is it really intentional to install them?

### What version of the PMIx Reference Library are you using? 
4.2.3 (and 4.2.4rc1)

### Describe how PMIx was installed 
Building the Fedora package from source:

```
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --runstatedir=/run --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --prefix=/usr --sysconfdir=/etc/pmix --disable-static --disable-silent-rules --enable-ipv6 --enable-shared --with-munge
```

**Comment by rhc54** [comment]
Yes it is intentional - we expose them so that PRRTE can access them. It's part of a code reduction effort where we avoid having copies of many of those functions in both PMIx and PRRTE. We don't necessarily need _all_ of them, but it was easier to simply expose them instead of trying to cherry-pick the duplicates one by one.

**Comment by opoplawski** [comment]
Okay, thanks for the confirmation.
