### ISSUE TITLE
python bindings failing spawn with non-supported

### ISSUE THREAD

**Issue by naughtont3** [openpmix/openpmix#3036]
## Background information

It seems the changes in March may have caused a problem with the python bindings.  We are seeing an existing test fail with spawn `NOT-SUPPORTED` after upgrade to latest openpmix.  

### What version of the PMIx Reference Library are you using? 

 - openpmix master @ 5b883068 
 - prrte master @ ef659d7ec3

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

Still testing to try and pinpoint but looks like the initialization is off and the `pmixservermodule` does not return the `spawn` key, so thinks it is now supported.

```shell

bash:$ prte --report-uri /tmp/dvm.uri &
[1] 28330
bash:$ DVM ready

bash:$ prun --dvm-uri file:/tmp/dvm.uri --np 2 /usr/bin/hostname
login06
login06
bash:$ 
bash:$ python3 tiny2.py 
init RC 0
spawn RC -47
ERROR -  NOT-SUPPORTED
bash:$ prun --dvm-uri file:/tmp/dvm.uri --np 2 /usr/bin/hostname
login06
login06
bash:$ pterm --dvm-uri file:/tmp/dvm.uri
TERMINATING DVM...DONE
[1]+  Done                    prte --report-uri /tmp/dvm.uri
bash:$ 
```

```
bash:$ cat tiny2.py 
import pmix, sys
tool = pmix.PMIxTool()
rc,proc = tool.init( [ {"key": pmix.PMIX_SERVER_URI, "value": "file:/tmp/dvm.uri", "val_type": pmix.PMIX_STRING}])
print("init RC", rc)
app = { 'cmd':"/usr/bin/hostname", 'maxprocs':2, 'my_id': 1}
info = []
rc,nspace = tool.spawn(info, [app])
print("spawn RC", rc)
if rc != pmix.PMIX_SUCCESS:
    print("ERROR - ",tool.error_string(rc))
    sys.exit(1)

print("DONE")
sys.exit(0)
```

**Comment by naughtont3** [comment]
note, did quick check with previous commit before python/binding change in march(214d5dffd1d2798baa96f5ce0c3085051903659a) and above check was fine.

**Comment by rhc54** [comment]
I doubt that commit caused this problem. It is like due to a later change I made to support scheduler integration. I suspect I need a corresponding change in the core code to deal with the case where a tool is calling an API but hasn't defined a server module function for supporting it. Kind of tricky wen using the Python bindings as the bindings in fact do define a module entry point - they just return "not supported" if the host hasn't defined the corresponding Python module function.

Anyway, I'll fix it next week when I return.

**Comment by naughtont3** [comment]
OK, did a bit more testing and "learned" a couple thing.
1.  Do not see `make install` problem on Centos 7.9 VM (but did need `pip3 install --user Cython` to install a python3 module)
2. Do not see `make install` problem if you remove the installdir from `PYTHONPATH` when running the `python3 setup.py...` during `make install`. (thanks Wael for spotting this diff)
3. But consistently saw `make install` on Ubuntu (and SLES olcf systems) unless add the `mkdir -p` bit

But it looks like you merged this. But figured I'd add a bit more info to ticket for trails.

**Comment by naughtont3** [comment]
> But it looks like you merged this. But figured I'd add a bit more info to ticket for trails.

Opps, nevermind i misspoke, the above merge was for a diff PR

**Comment by naughtont3** [comment]
@rhc54 So after #3037 the spawn is working, but I am not getting a registered handler called now.  We register for a job-exit event and that never gets fired.  If we kill the waiting process and run again, the event handler fires for the previously exited job, but not never for the current invocation of the Tool's spawned processes.

Basically, the test program calls following to set a global variable that we wait on to decide when we are "done" (set via the `done_handler`).
```
rc,myhandle = tool.register_event_handler( [pmix.PMIX_EVENT_JOB_END], None, done_handler )
```

I'm attaching a log and reproducer for clarity.
 - [dbg-log.txt](https://github.com/openpmix/openpmix/files/11314471/dbg-log.txt)
 - [sleepy2.c.txt](https://github.com/openpmix/openpmix/files/11314484/sleepy2.c.txt)
 - [simple_donehandler.py.txt](https://github.com/openpmix/openpmix/files/11314485/simple_donehandler.py.txt)

**Comment by rhc54** [comment]
I'll have to take a look in a bit, but obviously the handler is firing for the C-based tools since the debugger tests are passing. So the question is: is the event getting trapped in the bindings?

My immediate thought would be to check the Python tool and ensure that it isn't blocked somewhere such that the event is firing, but the tool isn't promoting it thru the bindings. Put a big print statement in the bindings where events are recvd and see if it appears - that would mean that the event is being passed back to you, but the Python progress thread isn't shifting it to where your handler can be called.

**Comment by rhc54** [comment]
One thing immediately leaps out from your donehandler reproducer - you don't specify the nspace of the job you want to be notified about. I suspect that is the problem. I'll check, but I doubt you can just say "tell me whenever any job exits" as that is too general.

`prun` is working fine, so the job complete notification is working.

**Comment by rhc54** [comment]
See fix [here](https://github.com/openpmix/openpmix/pull/3056)

**Comment by naughtont3** [comment]
Confirm #3056 resolved issue
