### ISSUE TITLE
TCP transport no in v5.0.1

### ISSUE THREAD

**Issue by miesav** [openpmix/openpmix#3158]
## Background information

openpmix 5.0.10

Built from Github source tarball

CentOS 7/Rocky 9 on vmWare ESXi 7.
S2600TPR
Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Ethernet/TCP

-----------------------------

## Details of the problem

configure on 5.0.1 outputs TCP transport as "no". 

checking if we are on Linux with TCP... no
...

Transports
-----------------------
Cisco usNIC: no
HPE Slingshot: no
NVIDIA: no
OmniPath: yes
Simptest: no
TCP: no

Version 4.2.6 seems to pick it up correctly on both systems.

Full config log:

[config.log](https://github.com/openpmix/openpmix/files/12592867/config.log)

**Comment by rhc54** [comment]
😆 Well, both release versions are actually correct. The reason is that I haven't yet implemented the TCP support (at least, not for production) and so the component is disabled. At one point I was actually removing the component prior to release, but then decided I really should leave it there for motivation.

Version 4.2.6 is correctly reporting the presence of the component, but the component doesn't actually do anything - which seemed misleading. So in v5 the component correctly indicates we don't yet provide PMIx "fabric" support for TCP.

Doesn't mean we won't use TCP - it just means that the `PMIx_Fabric_xxx` APIs won't return anything for TCP interconnect.

**Comment by miesav** [comment]
Thank you for the clarification! Was just wondering what was the difference.
