### ISSUE TITLE
Update from pmix 4.1.2 to 4.1.3 breaks ABI

### ISSUE THREAD

**Issue by opoplawski** [openpmix/openpmix#3163]
## Background information

Fedora updated pmix from 4.1.2 to 4.1.3 to fix CVE-2023-41915.  Unfortunately this broke openmpi:
```
mca_base_component_repository_open: unable to open mca_pmix_ext3x: /usr/lib64/openmpi/lib/openmpi/mca_pmix_ext3x.so: undefined symbol: pmix_value_load 
```
This was rather unexpected in a patch level release.

### What version of the PMIx Reference Library are you using? 
4.1.3

### Describe how PMIx was installed 
Fedora package

There were a lot of removed symbols apparently:
```
$ abipkgdiff --d1 pmix-debuginfo-4.1.2-5.fc39.x86_64.rpm --d2 pmix-debuginfo-4.1.3-1.fc40.x86_64.rpm --devel1 pmix-devel-4.1.2-5.fc39.x86_64.rpm --devel2 pmix-devel-4.1.3-1.fc40.x86_64.rpm pmix-4.1.2-5.fc39.x86_64.rpm pmix-4.1.3-1.fc40.x86_64.rpm
================ changes of 'libpmix.so.2.5.2'===============
  Functions changes summary: 34 Removed, 6 Changed (313 filtered out), 36 Added functions
  Variables changes summary: 2 Removed, 47 Changed (73 filtered out), 16 Added variables

  34 Removed functions:

    [D] 'function pmix_status_t pmix_argv_append_nosize(char***, const char*)'    {pmix_argv_append_nosize}
    [D] 'function pmix_status_t pmix_argv_append_unique_nosize(char***, const char*)'    {pmix_argv_append_unique_nosize}
    [D] 'function char** pmix_argv_copy(char**)'    {pmix_argv_copy}
    [D] 'function int pmix_argv_count(char**)'    {pmix_argv_count}
    [D] 'function void pmix_argv_free(char**)'    {pmix_argv_free}
    [D] 'function char* pmix_argv_join(char**, int)'    {pmix_argv_join}
    [D] 'function pmix_status_t pmix_argv_prepend_nosize(char***, const char*)'    {pmix_argv_prepend_nosize}
    [D] 'function char** pmix_argv_split(const char*, int)'    {pmix_argv_split}
    [D] 'function char** pmix_argv_split_with_empty(const char*, int)'    {pmix_argv_split_with_empty}
    [D] 'function int pmix_cmd_line_add(pmix_cmd_line_t*, pmix_cmd_line_init_t*)'    {pmix_cmd_line_add}
    [D] 'function int pmix_cmd_line_create(pmix_cmd_line_t*, pmix_cmd_line_init_t*)'    {pmix_cmd_line_create}
    [D] 'function int pmix_cmd_line_get_argc(pmix_cmd_line_t*)'    {pmix_cmd_line_get_argc}
    [D] 'function char* pmix_cmd_line_get_argv(pmix_cmd_line_t*, int)'    {pmix_cmd_line_get_argv}
    [D] 'function int pmix_cmd_line_get_ninsts(pmix_cmd_line_t*, const char*)'    {pmix_cmd_line_get_ninsts}
    [D] 'function char* pmix_cmd_line_get_param(pmix_cmd_line_t*, const char*, int, int)'    {pmix_cmd_line_get_param}
    [D] 'function int pmix_cmd_line_get_tail(pmix_cmd_line_t*, int*, char***)'    {pmix_cmd_line_get_tail}
    [D] 'function char* pmix_cmd_line_get_usage_msg(pmix_cmd_line_t*)'    {pmix_cmd_line_get_usage_msg}
    [D] 'function bool pmix_cmd_line_is_taken(pmix_cmd_line_t*, const char*)'    {pmix_cmd_line_is_taken}
    [D] 'function int pmix_cmd_line_make_opt3(pmix_cmd_line_t*, char, const char*, const char*, int, const char*)'    {pmix_cmd_line_make_opt3}
    [D] 'function int pmix_cmd_line_make_opt_mca(pmix_cmd_line_t*, pmix_cmd_line_init_t)'    {pmix_cmd_line_make_opt_mca}
    [D] 'function pmix_status_t pmix_info_list_add(void*, const char*, void*, pmix_data_type_t)'    {pmix_info_list_add}
    [D] 'function pmix_status_t pmix_info_list_convert(void*, pmix_data_array_t*)'    {pmix_info_list_convert}
    [D] 'function void pmix_info_list_release(void*)'    {pmix_info_list_release}
    [D] 'function void* pmix_info_list_start()'    {pmix_info_list_start}
    [D] 'function pmix_status_t pmix_info_list_xfer(void*, const pmix_info_t*)'    {pmix_info_list_xfer}
    [D] 'function int pmix_mca_base_cmd_line_process_args(pmix_cmd_line_t*, char***, char***)'    {pmix_mca_base_cmd_line_process_args}
    [D] 'function int pmix_mca_base_cmd_line_setup(pmix_cmd_line_t*)'    {pmix_mca_base_cmd_line_setup}
    [D] 'function void pmix_mca_base_cmd_line_wrap_args(char**)'    {pmix_mca_base_cmd_line_wrap_args}
    [D] 'function pmix_status_t pmix_setenv(const char*, const char*, bool, char***)'    {pmix_setenv}
    [D] 'function int pmix_sync_wait_mt(pmix_wait_sync_t*)'    {pmix_sync_wait_mt}
    [D] 'function void pmix_value_load(pmix_value_t*, void*, pmix_data_type_t)'    {pmix_value_load}
    [D] 'function pmix_status_t pmix_value_unload(pmix_value_t*, void**, size_t*)'    {pmix_value_unload}
    [D] 'function pmix_status_t pmix_value_xfer(pmix_value_t*, const pmix_value_t*)'    {pmix_value_xfer}
    [D] 'function int pmix_vpmix_snprintf(char*, size_t, const char*, __va_list_tag*)'    {pmix_vpmix_snprintf}
```

**Comment by ggouaillardet** [comment]
If this is related to https://github.com/open-mpi/ompi/issues/10416, then only subroutines that are **not** part of the PMIx 4 standard have been removed, which means correct PMIx 4 programs are not impacted.

**Comment by rhc54** [comment]
Looking back at the commit log, it appears that I missed adding a number of commits to the NEWS - since v4.1.2 was supposed to be the end of the series, I was adding commits to that branch solely to help it track changes in the Standard and critical changes in the code base for those wanting to download the "head" of the branch. Wasn't intended for a "release".

I will reiterate (from our prior discussion about this) that removing non-public interfaces doesn't constitute "breaking the ABI". Gilles is correct - OMPI was impacted solely because it was using non-public functions instead of limiting itself to only the published ABI. His patch for OMPI fixed that problem, but that patch has not yet been included in an OMPI release (coming soon, I believe). You'd encounter similar "ABI breakage" reports from most OMPI releases as the internal functions are free to change, and often do.

This is why I added a PMIx ABI checker script to help those who care - it only checks the published ABI 😄 

Anyway, I don't see a clear solution to the problem here. The public ABI is consistent between the releases. I could try and roll everything back to v4.1.2 and then add _only_ the CVE-related patch, but that doesn't seem worthwhile. Frankly, the v4.1 series isn't even supported any more - I only support the current series (v5.0) and one back (v4.2). I only posted releases for the older series because people were trying to patch it themselves instead of update - and I noted (quite clearly) that these older updates were _not_ supported:

> Note that I do so without making any changes to our support policy - these older versions _are not supported_, so please don't raise issues should you encounter problems when using them. I'll just advise you to update to a supported series (v4.2 or v5.0).

Unfortunately, all new series (v4.2, etc) are also not going to include those non-public ABI functions that the older OMPI release used. So updating PMIx series won't solve this particular problem - you need to update OMPI. You might want to push them to get that release out?

**Comment by rhc54** [comment]
I guess one option would be to add the CVE-related patch to your own v4.1.2 code and use that for your release. I honestly don't know how cleanly it would apply - but it might be doable, and then you'd have a version that continues to include those non-public interfaces. 🤷‍♂️  No guarantees, but you are welcome to try it.

**Comment by opoplawski** [comment]
At this point Fedora is going to rebuild deps.
