### ISSUE TITLE
Attempt to realloc stack variables during spawning

### ISSUE THREAD

**Issue by RaymondMichael** [openpmix/openpmix#3244]
This is with OpenPMIx 4.2.6.

Consider the following example.

{
  char *args[2] = {"0", NULL};
  pmix_app_t app;
  app.argv = args;
  ...
  PMIx_Spawn(NULL, 0, &app, 1, nspace);
}

pmix_client_spawn.c:215 calls PMIx_Argv_prepend_nosize() which attempts to realloc() app.argv to place app.cmd at the head of it. It's a stack variable, so the realloc() fails and the code aborts.

**Comment by rhc54** [comment]
Hmmmm...I haven't encountered that before, and I could swear I have used stack `app` variables before. Let me play with it a bit - if it truly is as you report, then there may be nothing we can do about it other than say "don't do that".

**Comment by RaymondMichael** [comment]
One solution would be to copy the app's array and then grow the copy.

**Comment by rhc54** [comment]
Yeah...have to think about that one a bit. There may be some unintended consequences of creating that separation. Offhand, though, it does sound like a potential solution.

**Comment by rhc54** [comment]
Well, I ran this thru the old brain and a couple of test cases, and I confess I'm a little stumped. Your suggested solution sounds plausible, but runs into a problem on your test example because the `app` structure isn't initialized. True, in some environments the stack will default to zero's, but definitely not always.

This causes a problem when trying to copy the `pmix_app_t` as you hit garbage, which then causes us to merrily run across memory. Of course, we'd have the same problem when trying to use those fields, so that isn't a deal breaker - just annoying.

What it does do is raise a question in my mind of "correct" programs. Should we consider the assignment in your example to constitute an "incorrect" program? True, you can do it in C - but there are lots of things you _can_ do that in fact are incorrect programs.

The following, in contrast, will _always_ lead to a correct program:
```c
pmix_app_t app;

PMIX_APP_CONSTRUCT(&app);
PMIX_ARGV_APPEND(app.argv, "0");

PMIx_Spawn(NULL, 0, &app, 1, nspace);
}
```
So I'm debating about the path forward. If we introduce the copy here, then we pretty much need to do it behind all the APIs for consistency - but that means the user no longer has to "hold" the input variables on non-blocking calls until the callback occurs since we will always copy the inputs, so that's a significant change in behavior. It also means some significant time and memory footprint penalties when passed large arrays.

Or we could document what constitutes "correct" vs "incorrect" input, and trust the normal error returns to help educate the user. Probably going to eventually generate heated arguments over that one.

Meantime, we already have people raising concerns over speed and memory footprint...and the copy solution is a step in the wrong direction towards silencing them.

Sigh - plumbing is so much fun! Going to let this one percolate for awhile in the hope that a median solution emerges.

**Comment by rhc54** [comment]
Well, I decided to give the "copy" approach a shot, at least just for "spawn", to see how bad it turned out to be. Wow, what a mess. I'm not sure how much impact it will have on spawn performance, but it certainly proved challenging to ensure we didn't spring a memory leak.

It was bad enough that I think I'll hold off on doing this for any more APIs for now. Maybe some alternative will come to light.

**Comment by rhc54** [comment]
Sigh - after all these years, one should know better than to make design decisions while tired, under time pressure, and ill. 🤷‍♂️ 

Turns out this isn't quite as bad as it at first appears. I do need, however, to refactor the code a bit to take advantage of the internal object "copy" support - will make the code far more maintainable. Will try to get to that soon. Meantime, the referenced commit should at least address the problem.

Thanks for pointing the problem out! Nobody had tripped over it for eight years - somewhat surprising, really.
