### ISSUE TITLE
How to process cmd and argv[0] correctly in pmix_server_spawn_fn_t

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#3321]
### What version of the PMIx Reference Library are you using?
v5.0.1

-----------------------------

In ParTec's PMIx host server implementation of the spawn interface, I assumed until now, that `app->cmd` and  `app->argv[0]` is always the same and so only `app->argv[0]` has been used as the executable for the app. Now playing around with `prefix` I realized, that this assumption is not true.

@sonjahapp nicely tried to investigate the openpmix code to figured out how it is intended to work and here are her findings:

- `cmd` is passed as the user defined it (if `cmd` is not set, an error is reported)

- It is checked, whether (optional) `argv` is given
  - If it is NOT, then the executable name is extracted from `cmd` and written into `argv[0]`.
  - If it is, then it is checked whether `argv[0]` and `cmd` are identical
    - If they are NOT, then the name of the executable is extracted from `cmd` and inserted into `argv` as `argv[0]`

Later than, `PMIX_PREFIX` is somehow integrated into `argv[0]` but how exactly remained unclear.

So here are my questions:

- Are the descriptions correct?
- Why is it done that way?

And the most important one from the title:

- How is this intended to be used in `pmix_server_spawn_fn_t`? I can only use one executable, should I use `cmd` or `argv[0]`? And what to do with the prefix? Is it already applied? Do I need to apply it? And if so, to what?

So you see, I am pretty lost in the dark and would appreciate very much, if you lead me to the light. Thanks in advance.

**Comment by rhc54** [comment]
Hi Stephan! I was just thinking about you folks the other day because I hadn't heard from you in awhile - hope all is going well.

Reviewing the code, I don't think the descriptions are quite correct. What I see is:

* if cmd is passed, then we use it
* if neither cmd nor argv is passed, then we return an error

We don't seem to correctly handle the case where cmd is NULL and argv is not NULL - we should set the cmd to argv[0], and then replace argv[0] with its basename. Instead, we would segfault. I'll have to fix that one.

At that point in the code, cmd has been set - one way or another.

* if argv is NULL, then we put the basename of cmd as argv[0]
* if argv is not NULL, then we check the basename of argv[0] against the basename of cmd. if those are not the same, we replace argv[0] with the basename of cmd.

This is done to match the semantics for the `exec` call (in whatever form one uses), and so that the app - if it looks at its argv[0] - sees its expected name, as per convention. This is what my exec looks like:
```c
    execve(app->cmd, app->argv, env);
```
I suppose we could have let the basename of argv[0] override the basename of cmd, or we could error out if they don't match. We just opted for this approach. I'm open to suggestion on the matter. Never actually had it come up as a problem.

I don't see any place where we do something with prefix. There is an attribute:
```
#define PMIX_PREFIX                         "pmix.prefix"           // (char*) prefix to use for starting spawned procs
```
but that just gets passed to the host - the PMIx library doesn't do anything with it. The purpose of it is to allow the user to indicate where some libraries and/or binaries might be found. For example, if an MPI app wanted to point the RM at where libmpi might be found, they could specify a prefix where the MPI implementation was installed, and the host could add the prefix/lib location to LD_LIBRARY_PATH.

Frankly, I've never used it, and I don't see that PRRTE supports it. People generally set those envars themselves and see no need to pass such things via the spawn cmd (unless they include it as an envar). I would personally ignore it, or you could set the paths accordingly if you prefer.

Note that there is a PMIX_PREFIX envar, and we do support that - if someone relocates the PMIx library, we realign some critical internal data structures using that envar. Has nothing to do with spawn, though your host environment might need to be aware of it when launching its remote daemons to ensure it gets propagated properly so the daemons can find the relocated library.

**Comment by krempel-pt** [comment]
Hi Ralph. Yeah, we are all quite busy at the moment, since some projects are close to be finished and much reporting and stuff has to be done. But that's the business, so all fine. Hope you are well, too.

Thank you very much for the detailed explanation, so it seems like we did especially misunderstand the meaning of this prefix info field, might be a point for another clarification in the standard.

If will try to adapt our implementation to what you explained in the next few days and come back with further question if they are rising. Will let this issue open that long.

**Comment by sonjahapp** [comment]
Hi Ralph!

Thank you also from my side! Great to hear from you.

Based on your explanation, I have another question regarding the `PMIX_PREFIX` attribute for `PMIx_Spawn`:
The PMIx 5.0 standard says:

>PMIX_PREFIX "pmix.prefix" (char*)
>         Prefix to use for starting spawned processes - i.e., the directory where the executables can be found.
*from PMIx 5.0 standard, page 163*

With my MPI library developer "glasses" on, I've interpreted this PMIx spawn attribute to match what is required for the `path` Info key that can be passed to `MPI_Comm_Spawn(_multiple)`:

>"path": Value is a directory or set of directories where the implementation should look for
>the executable. The format of "path" is determined by the implementation.
*from MPI 4.1 standard, page 527*

My thought was: If I pass the `PMIX_PREFIX` attribute to `PMIx_Spawn` with the value that an MPI user provided for the Info key `path` on `MPI_Comm_spawn(_multiple)`, we should be able to locate the executable for the spawn in the process manager even if `cmd` just contains the basename and the actual executable is `<path>/basename`.

Based on your explanation about `PMIX_PREFIX` from above, I see that (probably?) this was a misinterpretation on my side? If so, I agree with Stephan: The purpose of this attribute should be clarified in the PMIx standard (and I need to fix the PMIx-spawning support in our MPI library ParaStation MPI and upstream in MPICH in that regard :see_no_evil:).

**Comment by rhc54** [comment]
Sounds like a reasonable interpretation . As a (retired) MPI developer, I'm a little concerned about what happens with `LD_LIBRARY_PATH`. If we take the `prefix` as only providing a path to the `cmd`, then are we leaving the library path dangling? Hence my explanation above.

On the other hand, PMIx isn't an MPI system - it is agnostic. We already provide an envar mechanism for use in `PMIx_Spawn`, and one could adjust the library path that way.

So at least for now, I'd go with your initial interpretation as that is consistent with the exact wording in the Standard and ignore my explanation. As I said, I haven't actually implemented support for that attribute anywhere, so nobody will be impacted. If the Standard folks want to go a different way, we can deal with that later (and argue about the change since it _will_ then impact things).

Make sense?

**Comment by rhc54** [comment]
Thinking about it some more, and my response to your initial question really makes no sense. The prefix provides a path to your executable, not the MPI library. So using it to set `LD_LIBRARY_PATH` would be the wrong thing to do.

@sonjahapp's interpretation is the correct one to use - please ignore my misdirection.

**Comment by rhc54** [comment]
Might as well do it in the library where we are already adjusting cmd/argv. (in `src/client/pmix_client_spawn.c`). I'll post a PR shortly. We need to deal with it in both the `job_info` and individual apps - i.e., if given in the former, then default to using it in each unless the app also includes it.

**Comment by krempel-pt** [comment]
That's great, thanks a lot, Ralph.

**Comment by krempel-pt** [comment]
Hello Ralph,

reading in the standard once again, I am not sure that it is the best idea to process the prefix in the library. It says
> PMIx libraries are not required to directly support any attributes for this function. However, any provided
attributes must be passed to the host environment for processing.
> Host environments are required to support the following attributes when present in either the job_info or the
info array of an element of the apps array:

So it is required for the library to pass these infos (one of them is `PMIX_PREFIX`) to the host server and is is required for the host server to support those.

If the library already processes the prefix itself (which is not mentioned in the standard) AND passes it to the host server as required, how can the host server know, that the prefix is already applied?

Imagine a user wants to spawn an executable: `/home/user/a/b/a/b/exe`
He spawns with `cmd='a/b/exe'`, `PMIX_PREFIX='a/b/'`, `PMIX_WDIR='/home/user'`.
In that case the library will pass to the host `cmd='a/b/a/b/exe'`, `PMIX_PREFIX='a/b/'`, `WDIR='/home/user'` and the host cannot know, if `/home/user/a/b/a/b/exe` or `/home/user/a/b/a/b/a/b/exe` shall be executed.

**Comment by rhc54** [comment]
I can certainly remove it from the info's passed up to the host - I have to copy them anyway, so it is easy to simply remove that one. Just seems like it's easier to support it in the library if I'm already modifying the cmd/argv to ensure conformance to the expected alignment between the two.

We can modify the standard as required to clarify it. I'm not concerned there.

**Comment by rhc54** [comment]
We can add some words to the standard to the affect that "if the implementation handles the prefix, then it must remove the PMIX_PREFIX attribute before passing the keys up to the server. If the server sees a PMIX_PREFIX key, then it must handle it"...or something like that.

**Comment by krempel-pt** [comment]
> We can add some words to the standard to the affect that "if the implementation handles the prefix, then it must remove the PMIX_PREFIX attribute before passing the keys up to the server. If the server sees a PMIX_PREFIX key, then it must handle it"...or something like that.

That sounds good to me. Will you take care about that or shall I open an issue at pmix-standard?

**Comment by rhc54** [comment]
Would you mind doing it? I think you should receive the credit for raising the question in the first place 😄

**Comment by krempel-pt** [comment]
Thanks, too much honor. ;-)

Here it is: https://github.com/pmix/pmix-standard/issues/506
