### ISSUE TITLE
Second PMIx application missing attributes

### ISSUE THREAD

**Issue by dgloe-hpe** [openpmix/openpmix#3347]
### What version of the PMIx Reference Library are you using?
4.2.9

### Describe how PMIx was installed
RPMs built from a git clone

### Please describe the system on which you are running

* Operating system/version: SLES 15 SP5
* Computer hardware: VM
* Network type: VM

-----------------------------

## Details of the problem

The mpich team reported an issue on ANL where if they launch a shell script with PALS which runs multiple PMIx applications, only the first one has access to values like PMIX_APPNUM. I was able to reproduce it, and it seems like the second application has some problem initializing "ds21", so it can't read any of the values provided by PALS.

My minimal reproducer follows:

pmix_appnum.c:
```
#include <stdio.h>
#include <unistd.h>
#include <pmix.h>

int main() {
    pmix_proc_t proc;
    pmix_status_t rc = PMIx_Init(&proc, NULL, 0);
    if (rc != PMIX_SUCCESS) {
        printf("PMIx_Init failed: %d\n", rc);
        return 1;
    }

    printf("I am rank %d in namespace %s\n", proc.rank, proc.nspace);

    pmix_value_t *val = NULL;
    rc = PMIx_Get(&proc, PMIX_LOCAL_RANK, NULL, 0, &val);
    if (rc != PMIX_SUCCESS) {
        printf("PMIx_Get PMIX_LOCAL_RANK failed: %d\n", rc);
        return 1;
    }

    printf("PMIX_LOCAL_RANK is %u\n", val->data.uint16);

    rc = PMIx_Get(&proc, PMIX_APPNUM, NULL, 0, &val);
    if (rc != PMIX_SUCCESS) {
        printf("PMIx_Get PMIX_APPNUM failed: %d\n", rc);
        return 1;
    }

    printf("PMIX_APPNUM is %u\n", val->data.uint32);

    return 0;
}
```

test.sh:
```
#!/bin/bash
./pmix_appnum
./pmix_appnum
```

```
sles15sp5:~/pals # ./mpiexec -n 1 -hosts localhost --pmi=pmix ./test.sh
I am rank 0 in namespace pals.pmix.296853e9-cf59-4a76-afab-42d75005bf85.(null)
PMIX_APPNUM is 0
I am rank 0 in namespace pals.pmix.296853e9-cf59-4a76-afab-42d75005bf85.(null)
PMIx_Get PMIX_APPNUM failed: -46
sles15sp5: rank 0 exited with code 1
```

I was able to get more details by setting gds_base_verbose = 10 in /etc/pmix-mca-params.conf.
With that, I can see that the second application wasn't able to initialize ds21, though there isn't an obvious error message explaining why.

```
[sles15sp5:22061] mca:gds:select: checking available component ds21
[sles15sp5:22061] mca:gds:select: Querying component [ds21]
[sles15sp5:22061] pmix:gds:dstore init
[sles15sp5:22061] gds_ds21_lock_pthread.c:151:pmix_gds_ds21_lock_init local_size 1
[sles15sp5:22061] dstore_segment.c:158:pmix_common_dstor_attach_new_lock_seg: segment type 3, name pals.pmix.f374ba9f-f62d-46f2-bfe4-09d45e37be24.(null), id 0
[sles15sp5:22061] dstore_base.c:1807:pmix_common_dstor_finalize
[sles15sp5:22061] Final gds priorities
[sles15sp5:22061]       gds: ds12 Priority: 20
[sles15sp5:22061]       gds: hash Priority: 10
```

[pmix_appnum1.log](https://github.com/openpmix/openpmix/files/15406339/pmix_appnum1.log)
[pmix_appnum2.log](https://github.com/openpmix/openpmix/files/15406340/pmix_appnum2.log)

I would like to determine if there's something PALS can do to work around this issue, or if it's a problem with the openpmix library itself.

For reference, this is the mpich change that started the investigation: https://github.com/pmodels/mpich/pull/7001

**Comment by dgloe-hpe** [comment]
I added some PMIX_ERROR_LOGs to `pmix_gds_ds21_lock_init` and got this:

```
[sles15sp5:00492] PMIX ERROR: PMIX_ERR_NOT_FOUND in file gds_ds21_lock_pthread.c at line 258
```

Which corresponds to this code:
```
        if (false == idx_found) {
            rc = PMIX_ERR_NOT_FOUND;
            PMIX_ERROR_LOG(rc);
            goto error;
        }
```

**Comment by dgloe-hpe** [comment]
I added some debug pmix_output calls and the second application sees lock_idx_ptr[i] = 1, so it skips over it. Maybe something is supposed to reset that to 0?

```
sles15sp5:~/pals # ./mpiexec -n 1 -hosts localhost --pmi=pmix ./test.sh
[sles15sp5:05396] lock_item->num_locks = 1
[sles15sp5:05396] lock_idx_ptr[i] = 0
I am rank 0 in namespace pals.pmix.e52b5c1c-2b26-41ed-8dff-d700529c3cfb.(null)
PMIX_LOCAL_RANK is 0
PMIX_APPNUM is 0
[sles15sp5:05398] lock_item->num_locks = 1
[sles15sp5:05398] lock_idx_ptr[i] = 1
[sles15sp5:05398] PMIX ERROR: PMIX_ERR_NOT_FOUND in file gds_ds21_lock_pthread.c at line 260
I am rank 0 in namespace pals.pmix.e52b5c1c-2b26-41ed-8dff-d700529c3cfb.(null)
PMIx_Get PMIX_LOCAL_RANK failed: -46
sles15sp5: rank 0 exited with code 1
```

**Comment by rhc54** [comment]
Hmmm...the ds21 component disqualifying itself wouldn't be a problem - PMIx will just fall back to using the hash component. So that's not the problem.

Let me see if I understand what you are doing:

(a) start a single process, which means there is a single namespace that has one rank

(b) you then have that process start one pmix_appnum process and let that run to completion

(c) you then have that process start another pmix_appnum process, and that process fails when trying to retrieve the PMIX_APPNUM attribute

Is that correct? If so, I can see why there would be a problem. The PMIx server library only knows of one process - and since the initial process is a shell script that doesn't call PMIx_Init itself, the library only sees the first pmix_appnum execution. When that process terminates, the server library sees the only known rank go away - I'm not sure what state that leaves ds21 in. It might try and do some cleanup, could be that it leaves the lock for that process in some non-desirable state. After all, it saw the process terminate - no reason to worry about the state.

Now when another process suddenly appears in the same namespace, ds21 is surprised. Could be that it cannot recover, but regardless you get the "not found" error response.

One could argue that ds21 should handle this as a fault recovery. I know the OMPI folks do support recovery from process failures. However, in that case they actually go thru and reset the PMIx client entry for the recovered process. In this case, PMIx has no info as to what is happening.

You could try putting `PMIX_MCA_gds=hash` in the environment to disable the dstore and see if the hash component handles this better - the code paths are completely different there.

This seems like a very odd use-case. Certainly not something supported by the MPI standard. Is there some reason justifying support for this?

**Comment by rhc54** [comment]
BTW: you are quite correct that all will work fine if you `mpiexec` each pmix_appnum separately.

**Comment by dgloe-hpe** [comment]
In the original gist, they're running one MPI process in the background and start another one while the first is still running, but they get the same problem: https://gist.github.com/raffenet/0e86c77cf5a1a12eb8aa0a88e38a9dd8

I also thought this was odd, but they claim that it worked for other PMIx implementations.

exporting PMIX_MCA_gds=hash did work around the issue.

**Comment by rhc54** [comment]
By "other PMIx implementations", I take it you mean some PMIx-based starter other than PALS? So PALS would start their script, the script starts the daemon in the background and then fires off a "hello" MPI app?

The scenario is that you have two processes that are sharing the same PMIx rank. I gather from the script that both processes are actually running at the same time (and not sequentially as in your reproducer)? If so, then the problem is that the dstore probably doesn't support it - the locking system will fail because two procs are attempting to use the same lock.

Hence the hash component works fine as there is no locking involved.

FWIW: PMIx v5 and above uses a different method for shared memory - the dstore implementation is gone. You might try that and see if it behaves differently (it should - it just pushes the hash code into a shared memory region).

Seems odd, though, that it would work with PRRTE or Slurm and not PALs in that case. Not sure what role the launcher itself would play in it. I might give it a try with PRRTE and just verify that it works.

**Comment by rhc54** [comment]
FWIW: I just tested your simple reproducer with PRRTE and PMIx v4.2 - and it fails exactly the same way.

Given that we have moved away from dstore, I see no prospect for doing anything about this. I would recommend looking at PMIx v5, or simply forcing the hash component (which should be acceptable, I would think, given that this looks like something pretty experimental).

**Comment by rhc54** [comment]
Is there anything more to be done here?
