### ISSUE TITLE
PMIx Server: How to register minimal namespaces? Meaning of PMIX_REGISTER_NODATA?

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#3348]
The standard requires a host server to
> register all namespaces that will participate in collective operations with local processes. This means that the server must register a namespace even if it will not host any local processes from within that namespace if any local process of another namespace might at some point perform an operation involving one or more processes from the new namespace. This is necessary so that the collective operation can identify the participants and know when it is locally complete.

Usually, we put as much information into the namespace registration as possible. I wonder now, what is the minimal information that I need to provide to successfully register a namespace. The background is, that I want to avoid sending around information that will never be used on most of the nodes. For example when a process does a `PMIx_Spawn` and a new job is created on a new set of nodes, I need to register the parents namespace on the children's nodes and vice versa to enable fences over parents and children. But I doubt that the children need no know e.g. the executables and arguments of all apps in the parents job. So the question is, which information is really needed?

I stumbled over the attribute `PMIX_REGISTER_NODATA`, which sounds like I can mark the namespace as incomplete or something, but the only description of that attribute in the whole standard is "Registration is for this namespace only, do not copy job data." which is not very enlightening.

Am I on the right path with `PMIX_REGISTER_NODATA` or is that meant for something completely different? How can I find out the minimal set of information necessary to be passed into `PMIx_server_register_nspace()`?

**Comment by rhc54** [comment]
Hmmm...well, I note that the Standard does include this about `PMIx_Spawn`:

> By default, the spawned processes will be PMIx ``connected'' to the parent process upon successful launch (see Section \ref{chap:api_proc_mgmt:connect}
for details). This includes that (a) the parent process will be given a copy of the new job's
information so it can query job-level info without incurring any communication penalties, (b) newly spawned child processes will receive a copy of the parent processes job-level info, and (c) both the parent process and members of the child job will receive notification of errors from processes in their combined assemblage.

I believe that pretty clearly states that you have to provide a complete copy of the parent job's info. While many applications might not need to know the executables and arguments of the parent apps, there are some that might well want it. So it can get difficult if you try to edit out information.

I tend to err on the side of caution. Yes, it means extra data gets registered that might never be accessed - but it is impossible for me to tell which info that might be in advance, and having some library/app abort because I left something out is probably going to generate a negative reaction.

I imagine one could argue that the RM be allowed to identify what it provides in its documentation. From a user perspective, this isn't terribly useful as it hurts portability - but certainly an understandable position for an RM vendor to take. Personally, I would advocate for providing all the "usual" info - i.e., if you provide something to a newly spawned job, then you should provide it to the child job for consistency. Reduces the probability of complaints.

`PMIX_REGISTER_NODATA` simply tells the PMIx server that the host is informing it that this namespace exists and how many local procs there are, but doesn't want to register any additional job-level data about it. I don't use it myself, but IIRC I created it because someone was trying to do what you describe. Also IIRC, it didn't work out for the reasons I describe above.

**Comment by krempel-pt** [comment]
Ok, somehow makes sense, thanks for the quick reply. I think I will stop thinking in that direction for the moment and see how I can distribute as efficient as possible everything needed to provide a complete set of job information.
