### ISSUE TITLE
Question on handling temporary directories

### ISSUE THREAD

**Issue by krempel-pt** [openpmix/openpmix#3349]
Again this is a question that could as well go into the standard project, but I am asking here because more relevant for me is how it is intended and implemented in OpenPMIx.

There are a couple of temporary directory paths that can be passed by the host server:
- `PMIX_SERVER_TMPDIR` passed with `PMIx_server_init`
> Top-level temporary directory for all client processes connected to this server, and where the PMIx
server will place its tool rendezvous point and contact information.
- `PMIX_SYSTEM_TMPDIR` passed with `PMIx_server_init`
> Temporary directory for this system, and where a PMIx server that declares itself to be a system-level
server will place a tool rendezvous point and contact information.
- `PMIX_TMPDIR` in session realm
> Full path to the top-level temporary directory assigned to the session.
- `PMIX_NSDIR` in job realm
> Full path to the temporary directory assigned to the specified job, under `PMIX_TMPDIR`.
- `PMIX_TMPDIR` in node realm (for the local node)
> Full path to the top-level temporary directory assigned to the session.

It is clearly stated, that `PMIX_NSDIR` needs to be under `PMIX_TMPDIR`.
On the other hand the description of `PMIX_SERVER_TMPDIR` says it is the top level for all client processes connected to this server.

So it seams that the idea is to have `PMIX_NSDIR` under `PMIX_TMPDIR` under `PMIX_SERVER_TMPDIR`.

Actually I would say, the standard would allow `PMIX_TMPDIR` and `PMIX_SERVER_TMPDIR` to be the same directory, right?

Now I come to the more important questions, there are
- `PMIX_TDIR_RMCLEAN` in session realm
> The Resource Manager will remove any directories or files it creates in `PMIX_TMPDIR`.
- `PMIX_TDIR_RMCLEAN` in job realm
> The Resource Manager will remove any directories or files it creates in `PMIX_TMPDIR`

Is it correct, that both are related to `PMIX_TMPDIR` and not the second one to `PMIX_NSDIR`?

What is to be indicated by this switch? It somehow would make sense to me, if the host server can tell, whether it will cleanup the whole directory, so as well files that have not been created by the host server itself. But shouldn't it be natural for each server to not leave orphaned files behind?

And finally a general question: What does OpenPMIx expect concerning the temporary directories? Shall they exist before passing the names to the library? So is it the host servers responsibility to create and destroy all these temporary directories or is that managed by OpenPMIx?

**Comment by rhc54** [comment]
I'm guessing your cited statements all relate to the Standard? Probably needs a bit of a refresh in the language as we seem awash in "tmpdir" definitions 😄 

I had a chart on this hierarchy and included it in a presentation, but that was a while back now. Pretty sure it is out there somewhere, though I cannot recall where it got posted (someone recorded the presentation, IIRC). You also might want to look at the doc posted on the subject: https://docs.openpmix.org/en/latest/how-things-work/session_dirs.html

Note that your statement regarding "PMIX_NSDIR needs to be under PMIX_TMPDIR." There is no such requirement - as the doc indicates, it _usually_ would be placed there, but since you pass that info to the server/client anyway, it can be anywhere. Same for the `PMIX_PROCDIR`.

`PMIX_TMPDIR` is more of a legacy thing - it's where we started before the need arose for all these use-specific locations. I don't see us looking for that attribute any more in the code. I also note some internal inconsistencies have crept into the code over the years, so some cleanup is required (but won't restore use of this attribute as the use-specific ones are better).

The PMIx server library will automatically cleanup all files and directories that it creates. The idea of the `PMIX_TDIR_RMCLEAN` attribute was to indicate that PMIx doesn't need to do that - basically, there are cases where the environment provides a unique "tmpdir" for each PMIx server to use, and then the environment whacks that entire tree once it sees the process containing the server terminate. Glancing at the code, I'm not sure we ever implemented that attribute in PMIx, though having the server cleanup doesn't really harm anything. I'll put it on the list of things to review in case I missed it somewhere.

PMIx will create the directories if it needs to do so. We track whether or not we created them, and we only remove them if we did the creation. IIRC, PRRTE tends to create some of the highest level ones, and lets PMIx create the job-level ones - but I can't swear to that at the moment. Ultimately, it doesn't really matter - PMIx will use what it finds and create what is missing, and then cleanup whatever it creates.

The system tmpdir needs to be persistent and visible across sessions. It really is only used by a system server so we can know how to find its rendezvous file. It's one of those tricky things - e.g., if you want a tool to be able to query the system, then it has to know how to find the rendezvous file for a system-level server.

My own advice: always provide a unique location for each session to use as a server-level tmpdir, and then delete that entire tree when the session completes. You can never guarantee that someone completely cleans up - e.g., the process containing the PMIx server could segfault or abort without finalizing the server. Better to isolate and remove to be certain.

So to summarize, here is what I do (FWIW):

* identify a system tmpdir and pass that to each PMIx server via init. This needs to be some well-known location like `/tmp` (or you can put it somewhere else and set the environment `TMPDIR` location) so a tool started at the cmd prompt can know where to look for a system server. A PMIx server that is told to act as the system server will also then know where to put its rendezvous file for such a tool to find.
* when I use a launcher to start a job in the session (e.g., `mpirun`), then I have the launcher (and its daemons) create a server-level tmpdir (under the system tmpdir) and pass that to its local clients. This just provides some cross-mpirun isolation. I do the same thing for PRRTE DVM instances, for the same reason. If you don't want/need to do that, then you can set server tmpdir equal to the system tmpdir
* when spawning a job, I create the nsdir for that job (putting it under the server tmpdir) and the procdir for each local proc in that job (putting those under the nsdir) before registering it, and pass those locations along in the nspace registration info
* when the DVM or launcher terminates, I have their daemons remove the server tmpdir they created and all directories/files beneath it. Even though PMIx should have removed everything it created, it won't have removed the directories themselves because the daemon created it - and PMIx won't remove user-created files. So I ensure the daemons scour the area.

HTH

**Comment by krempel-pt** [comment]
Thanks a lot for the detailed answer.

Your doing sounds quiet reasonable to me, I think I will adapt it mostly.
