### ISSUE TITLE
PMIx Process Group construction with spawend processes on multiple nodes crashes (version 4.2.9)

### ISSUE THREAD

**Issue by sonjahapp** [openpmix/openpmix#3360]
## Background information

Hello again!

If I construct a PMIx Process Group that includes original and spawned processes on multiple nodes I observe a crash with version 4.2.9 (see below) whereas version 5.0.2 works fine.

### What version of the PMIx Reference Library are you using? 
- Tested with 4.2.9 and 5.0.2
- Used PRRTE 3.0.5

### Describe how PMIx was installed 
from a git clone

### Please describe the system on which you are running

* Operating system/version: Rocky Linux release 9.4
* Computer hardware: docker swarm cluster
* Network type:

-----------------------------

## Details of the problem

- After spawning some processes, *all* processes shall construct a PMIx Process Group (original and spawned processes) using `PMIx_Group_construct`
- Works on a single node with 4.2.9 and 5.0.2
- Works if original and spawned processes are on different nodes with 4.2.9 and 5.0.2
- Crashes with 4.2.9 if multiple nodes are used and the spawned processes are on the same node as at least one of the original processes:
   - `PMIX ERROR: PMIX_ERROR in file <...>/src/mca/common/dstore/dstore_base.c at line 938`
   - This case works with 5.0.2

Thanks a lot for the help!

**Comment by rhc54** [comment]
Just an FYI: the 4.2 series is locked down - no more patches expected to go into it. Focusing on supporting the 5.0 series and completing the 6.0 release this fall.

Also FYI: I'm concentrated at the moment on reworking the PMIx `Group` operations, extending them to handle a new "bootstrap" mode where not all eventual members are known by all parties. In the example of two primary participants, each will call "construct" and provide a list of additional members that the other primary participant doesn't know about. Those additional members get added to the group and included in the returned final group membership.

I'm also ensuring that the "group_construct" operation properly returns all job-level info, group info provided by participants, and info "put" by participants on remote scope (since local scope should already be covered by the PMIx server).

It's a fairly significant rework that I hope to commit to the `master` branch next week. Will not be backported to v5.x, only released in v6.0.

**Comment by sonjahapp** [comment]
Thanks for the outlook. I am currently shifting my work towards v5 anyway. Just thought it might be worth documenting my findings on 4.2 anyway. Since this issue will not be fixed, I close it.

The new bootstrap mode for process groups sounds really interesting. I think this should ease the group construction including original and spawned processes. I stumbled over the point that *all* participants have to be known everywhere for `PMIx_Group_construct` a few times already. Is the new mode covered in the PMIx standard? Or will it be covered in a future version?

**Comment by rhc54** [comment]
Hi @sonjahapp . Hope you are having a fun holiday! Just wanted to let you know that I completed the bootstrap support. Working on the doc, but can provide a simple explanation if it would be of use to you.
