### ISSUE TITLE
mpirun -xml option omits root xml element

### ISSUE THREAD

**Issue by david-edwards-linaro** [openpmix/openpmix#3450]
### What version of the PMIx Reference Library are you using?
OMPI 5.0.6

### Describe how PMIx was installed
tarball

### Please describe the system on which you are running

* Operating system/version: Ubuntu 22.04
* Computer hardware: single node x86_64

-----------------------------

## Details of the problem

`mpirun -xml -n 1 hello_c` produces output missing an xml root element (\<mpirun\> \</mpirun\> in OMPI < 5.0.0)

The same applies to `prterun --output=xml`

**Comment by rhc54** [comment]
Probably an easy fix, so I should manage to do it. Please be advised: as I stated on the mailing list multiple times, PMIx releases are approaching an end-state position. In other words, there are no plans for continued releases going forward.

So testing release candidates is CRITICAL - otherwise, even if I do produce a fix (which won't be on any guaranteed timeline), you will not see it in an official release. It will just be on the branch in the GitHub repo.

Please factor that into your plans. I believe there will indeed be ONE more release as there are (non-pmix) problems in OMPI that necessitate a re-release of their latest version, so I'll provide an update for their use.

**Comment by rhc54** [comment]
Beginning to get a glimmer of a possible solution, but before I spend a bunch of time on it - is this an actual problem of concern? Or are you just kicking tires to see what works?

I ask because one obvious answer is to just disable XML output altogether - much simpler solution if this isn't something anyone really cares about.

**Comment by rhc54** [comment]
Okay, I've done the best that I can without an enormous effort. The tool (e.g., `prterun`) will now output a start and end tag, and show_help output will _mostly_ be in XML format. Output that comes prior to our initializing the PMIx subsystem will _not_ be in XML, but will appear as plain text between the start and end XML tags. This will break an XML parser, but there is nothing to be done about it. Any output _after_ we init the subsystem will be correctly formatted.

Not perfect, but better than it was - and probably all that can/should be done. Appreciate the heads-up!
