### ISSUE TITLE
Runpath missing to installation prefix for Python bindings?

### ISSUE THREAD

**Issue by Apteryks** [openpmix/openpmix#3457]
## Background information

When building openpmix with `--enable-python-bindings` using GNU Guix, its `validate-runpath` verification phase fails like this:

```
starting phase `validate-runpath'
validating RUNPATH of 5 binaries in "/gnu/store/vkv4x0g1ak11s0mgzdm826gg9gmqyy0a-openpmix-4.2.8/lib"...
/gnu/store/vkv4x0g1ak11s0mgzdm826gg9gmqyy0a-openpmix-4.2.8/lib/python3.10/site-packages/pypmix-4.2.8-py3.10-linux-x86_64.egg/pmix.cpython-310-x86_64-linux-gnu.so: error: depends on 'libpmix.so.2', which cannot be found in RUNPATH ("/gnu/store/lp8ch4rn10whzyajnzv216d2a2v163c7-python-3.10.7/lib" "/gnu/store/zvlp3n8iwa1svxmwv4q22pv1pb1c9pjq-glibc-2.39/lib" "/gnu/store/zzpbp6rr43smwxzvzd4qd317z5j7qblj-gcc-11.4.0-lib/lib" "/gnu/store/zzpbp6rr43smwxzvzd4qd317z5j7qblj-gcc-11.4.0-lib/lib/gcc/x86_64-unknown-linux-gnu/11.4.0/../../..")
validating RUNPATH of 8 binaries in "/gnu/store/vkv4x0g1ak11s0mgzdm826gg9gmqyy0a-openpmix-4.2.8/bin"...
error: in phase 'validate-runpath': uncaught exception:
misc-error #f "RUNPATH validation failed" () #f 
phase `validate-runpath' failed after 0.0 seconds
```

I'd expect a runpath entry in the generated Python binding library pointing to the installation libdir, which is `/gnu/store/vkv4x0g1ak11s0mgzdm826gg9gmqyy0a-openpmix-4.2.8/lib`

### What version of the PMIx Reference Library are you using?
Version 4.2.8.

### Describe how PMIx was installed
Building from source from the tarball.

### Please describe the system on which you are running

* Operating system/version: Guix System, latest
* Computer hardware: x86_64

**Comment by rhc54** [comment]
Never even heard of that "phase" (or Guix, for that matter), so I'm afraid I'll be of no help resolving it. Have to hope someone more familiar with it can help. 🤷‍♂️

**Comment by Apteryks** [comment]
It's not a Guix issue per see; it's an issue flagged *by* Guix :-).  The problem appears to be that cython doesn't use the `ld` command available on PATH or doesn't actually link the stub loader it produces to the library.

I've found a workaround, which is to set the LDFLAGS environment variable, which appears to be honored by `cython`:
```scheme
              (add-after 'unpack 'set-LDFLAGS
                (lambda _
                  (setenv "LDFLAGS"
                          (string-append "-Wl,-rpath=" #$output "/lib"))))
```

It seems openmpix already cares a lot about these things, as evidenced by its `pmix_setup_wrappers.m4` macros; perhaps it could set LDFLAGS to the value of `--with-wrapper-ldflags` when `--enable-python-bindings` is used.

**Comment by rhc54** [comment]
You are welcome to provide a patch. I have no way to test this as I've never encountered a problem using the Python bindings as-is...and nor has any of the users of the bindings to-date. We are on a fair variety of systems, so this would appear to be something related to the environment you are using.

Happy to fix it, but as I cannot test that I'm doing the correct thing, probably best if someone else provide the patch. I can then verify it doesn't break others.

**Comment by rhc54** [comment]
FWIW: I wonder if this is more of a problem of the build environment attempting to test something without the necessary setup? The bindings have been available for a fair amount of time (I don't remember when I first wrote them, but it has been a few years), without encountering problems in build or time of use. However, we do require that you set `LD_LIBRARY_PATH` and `PYTHONPATH` correctly prior to using them.

When I see a `runpath` requirement, it usually reflects a desire to force the linkage to a specific library regardless of `LD_LIBRARY_PATH`. So I wonder if the issue here is that you're "verification phase" is simply attempting to use the bindings without properly setting the path envars? If so, that might reflect a difference in approach in the test as opposed to the build system - i.e., do we actually want the bindings hard-locked to the specific library?

Of course, I readily admit that I may not be correctly understanding the runpath issue 😄 

As for that reference: OMPI 1.4 is beyond ancient, and the comment is no longer accurate. PMIx (and OMPI, for that matter) statically builds all its plugins unless requested not to do so.

**Comment by rhc54** [comment]
Any updates? My sense is that this is a build system issue, perhaps conflicting with our expected usage model. Still not hearing anyone indicate there is a problem with our released Python bindings.

**Comment by Apteryks** [comment]
Hi,

Apologies for the slow response; it's complicated :-).

> When I see a `runpath` requirement, it usually reflects a desire to force the linkage to a specific library regardless of `LD_LIBRARY_PATH`. So I wonder if the issue here is that you're "verification phase" is simply attempting to use the bindings without properly setting the path envars? If so, that might reflect a difference in approach in the test as opposed to the build system - i.e., do we actually want the bindings hard-locked to the specific library?
> 
> Of course, I readily admit that I may not be correctly understanding the runpath issue 😄

In GNU Guix, every C/C++ library is typically built as a shared library, and a ld wrapper script available on `PATH` at build time ensures each linked library also gets a rpath entry baked into the ELF (by adding `-rpath $dir-of-library` for each library).  That is useful to find libraries in Guix since it doesn't use global fixed places to install libraries (e.g., the File Hierarchy Standard on traditional distributions), given each package gets installed to its own prefix, and is a bit nicer than having to maintain a correct LD_LIBRARY_PATH at all times.

The ld wrapper script will only add the -rpath options if the library is found at some expected place (called the "store", a cache of all package builds), so this doesn't work for example when linking a library found in the temporary build directory, as in this case:
```
gcc -shared -Wl,-rpath=/gnu/store/lp8ch4rn10whzyajnzv216d2a2v163c7-python-3.10.7/lib -fno-semantic-interposition build/temp.linux-x86_64-cpython-310/tmp/guix-build-openpmix-4.2.8.drv-0/pmix-4.2.8/bindings/python/pmix.o -L/tmp/guix-build-openpmix-4.2.8.drv-0/pmix-4.2.8/src/.libs -L/gnu/store/lp8ch4rn10whzyajnzv216d2a2v163c7-python-3.10.7/lib -lpmix -o build/lib.linux-x86_64-cpython-310/pmix.cpython-310-x86_64-linux-gnu.so
```

The Cython .so wrapper is linked with the freshly built `pmix` library, located under `/tmp/guix-build-openpmix-4.2.8.drv-0/pmix-4.2.8/src/.libs`.  In such cases, Guix currently depends on the build system to properly re-link the shared libraries against the *installed* libraries, which most build systems do (libtool does it, and so does cmake for example -- although the later doesn't truly relink but edits the RUNPATH from the binary directly for speed).

Since the library is built outside of the control of GNU autotools here (it's done by Cython), it seems it won't know it should relink it at install time.  I'm not sure if GNU autotools somehow can be told to do this for libraries created by external programs, but that's our problem here.

**Comment by rhc54** [comment]
Well, as I said earlier, if someone wants to submit a patch to address this, I'm certainly willing to evaluate it. We have required that `LD_LIBRARY_PATH` be correctly set since the project began and that is the standard method in HPC, so this sounds like something specific to the way Guix wants to operate. Might therefore need to be controlled via configure to avoid confusion elsewhere - would have to ponder that one.

**Comment by Apteryks** [comment]
If the build system was let to handle building/link the library, I think the current requirement about setting `LD_LIBRARY_PATH` could be dropped, as it would not longer be necessary.

**Comment by Apteryks** [comment]
I'm stretched thin and have a working workaround, so won't be providing patches for it, but I see value in this being implemented longer term.  I'll let you choose to keep this open or close it.

**Comment by rhc54** [comment]
Okay, then we'll just drop this. As I said, we've been using the HPC standard method based on `LD_LIBRARY_PATH` since the project began, and we'd have to think hard about the potential impact to existing users of making such a change (e.g., what does it do to `module` or `lmod`?). Minus users surfacing a problem, this feels like something specific to the way Guix has chosen to operate, and not a general concern. Given you have a solution for that environment, we should probably leave things as they are.
